### ISSUE TITLE
Create a Self class to house endpoints that can be called with self

### ISSUE THREAD

**Issue by jessemcbride** [ucfopen/canvasapi#108]
We have several methods scattered around different classes which can only be called using the active user (i.e. the API key owner). For example, `list_groups` in `User` only callls `/api/v1/users/self/groups`. Rather than having to instantiate a `User` object with `id  = "self"`, we should create a new class to manage these methods.

These should be accessible through `canvas.get_current_user()` or something similar.

**Comment by DanBrink91** [comment]
Would this be as simple as:
`def get_current_user(self):
	return self.get_user('self')`
