### ISSUE TITLE
Provide built-in way to validate API token

### ISSUE THREAD

**Issue by Thetwam** [ucfopen/canvasapi#113]
We used to have a built-in check that would validate API tokens right after creating a `Canvas` object. We removed this feature because the endpoint we were relying on to check wasn't always available to every user (I think it was getting all accounts for a user?).

While not every user can grab a list of accounts, as near as I can tell, every user can grab their own user object via `/api/v1/users/self` (Note this may tie into #108). This provides a reasonably reliable place to verify API tokens.

I'm hesitant to add this feature as a part of the `Canvas` object creation process. Perhaps a `verify_token` method on the `Canvas` class that a developer could call?

**Comment by jessemcbride** [comment]
I've been thinking about this and have come to the conclusion that it's beyond the scope of the library. We already provide the `InvalidAccessToken` exception - it's up to the developer how they want to handle that.

-- 

With regards to library scope, I know we've made some exceptions to the 1:1 coupling of library and API calls. As we've discussed, #112 falls under those exceptions. It's fair to ask why that's an okay exception to make and why this one isn't.  My reasoning is this: I think we should make special exceptions for helper functions when there is no other way to build those features with the current implementation of the library. 

Multithreaded support _cannot_ be written by a developer in conjunction with CanvasAPI without changing the internals of the library. However, a feature like this could easily be written by a third-party, as it doesn't require any internal modification.

I'm open to more discussion about this, of course, but as of right now I don't see a reason to add this.

**Comment by Thetwam** [comment]
Good point. I still think it has some value, though. Sure, a developer can replicate this on their own, but it's not immediately obvious how to do so.

At the very least, we should put some note in the docs that explain that the most reliable way to check an API key is to hit the `/users/self` endpoint.

**Comment by Thetwam** [comment]
After further in-person discussion, going to close this one.

Any time a request is made with an invalid API key, `InvalidAccessToken` is raised. A developer can quite easily handle that exception and react appropriately.

So long as our implementation of #108 appropriately raises `InvalidAccessToken`, I'll be satisfied.
