### ISSUE TITLE
Deprecate /api/v1 from Canvas constructor

### ISSUE THREAD

**Issue by jessemcbride** [ucfopen/canvasapi#115]
Currently we require `/api/v1/` to be appended to the end of an institution's Canvas URL when initializing the `Canvas` object.

We don't check if the URL is malformed in anyway, and as a result, sometimes unexpected behavior can present itself. We recently ran into this issue with one of our own applications where the base URL was set to `instructure.edu//api/v1/`.

We should implement a fix for this in two ways:

* Remove the `/api/version` requirement in the URL as we don't currently support targeting more than one API version
* Force URLs to be formatted properly (i.e. `*.someurl.com` with no trailing slash, `https://` or `http://` allowed) and manually append the `/api/v1/` string ourselves afterward

We should also warn the user that `/api/v1/` has been deprecated and is no longer required if they include it in their base URL.

**Comment by ssilverm** [comment]
Should for the next two versions issue a warning about deprecation if /api/v1 is appended.  Allow for both.  Third version remove support for /api/v1

**Comment by jessemcbride** [comment]
Note to self: Update documentation to reflect the API path is no longer necessary following this change.
