### ISSUE TITLE
File Download

### ISSUE THREAD

**Issue by DanBrink91** [ucfopen/canvasapi#119]
Add a method for downloading files to the File object

**Comment by jessemcbride** [comment]
Per our conversations about this in the office, I'm thinking we should have two methods: one to provide a download that writes directly to the machine and one that allows you to download it and keep it in memory.

**Comment by Thetwam** [comment]
Do those need to be separate methods? The code will be largely the same for both, just depends where it puts the file. I feel like an optional `path` argument would be sufficient. If provided, write the file to the path (and maybe return the handler?). Otherwise, just return the file directly.
