### ISSUE TITLE
JSONDecodeError when uploading a file

### ISSUE THREAD

**Issue by sigurdurb** [ucfopen/canvasapi#129]
I am getting an error when calling upload_comment for a submission on a html file. I am not sure what is wrong. Tried it both in test and real environments on my schools canvas instance.

It traces the error to this line.
https://github.com/ucfopen/canvasapi/blob/2c4016c071701bcef949685329acaec6115ffb3b/canvasapi/upload.py#L96

where kwargs is getting its value from the response:
```
kwargs = response.get('upload_params')
kwargs['file'] = file
```
But from the traceback the value of kwargs looks to be None later when it is passed on.
See Error traceback:
```
File "/usr/local/lib/python3.6/site-packages/canvasapi/submission.py", line 40, in upload_comment
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/canvasapi/upload.py", line 47, in start
    return self.request_upload_token(file)
  File "/usr/local/lib/python3.6/site-packages/canvasapi/upload.py", line 69, in request_upload_token
    return self.upload(response, file)
  File "/usr/local/lib/python3.6/site-packages/canvasapi/upload.py", line 96, in upload
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by sigurdurb** [comment]
Well, printing out kwargs is full of reasonable information but I have no idea why this is happening, maybe my schools canvas has some different setup regarding the file upload then this setup is setup for. Can somebody(@Thetwam or somebody) that has this working send me their pip freeze information? I just upgraded canvasapi so maybe this is some dependency thing, not sure what could be causing this.

**Comment by Thetwam** [comment]
Hey @sigurdurb,

I have been able to replicate the issue you are reporting. It works on an older instance of Canvas I tested it on, but not our production or test instances. I suspect there has been a change to the API that we will need to adapt to. Will investigate.

**Comment by jessemcbride** [comment]
@sigurdurb We've resolved this on our development branch. You can view the commit here: https://github.com/ucfopen/canvasapi/commit/e36e130c20abca5f99abfad4b192ab6521fdbfbc

Canvas recently updated their JSON response for one of the stages of the upload process to include special text to prevent JSON hijacking. Our fix strips this out before attempting to parse the JSON object. 

We'll be releasing this patch with a few other tweaks as 0.8.1 sometime this week. Until then, feel free to use our development build.

Thanks for catching this. Sorry about the inconvenience.

**Comment by sigurdurb** [comment]
@Thetwam  @jessemcbride 

The code runs through now. But the file does not appearing in the speedgrader in my test environment.

Maybe I have to include some params? seems like canvasapi only handles file name and file size at the moment. The api docs suggest that "/" is treated as part of the filename so I am using os.chdir and then calling the upload_comment on the os.path.basename. Since each students html file is in a directory structure like feedback/<canvas_login_id>/<ProjectName>/feedback.html
But I am not sure if that is enough, it might take awhile for it to get the upload url from Canvas to upload the file and then I have already used chdir to the next file.

The files I am trying to send are html file and am using params = {'content_type':'text/html'} But not sure I should be doing that. I already tried skipping that and it seems it does not matter.

How are you guys using this method? are all your files in the same folder as the script is running?

**Comment by sigurdurb** [comment]
@jessemcbride I tried submitting a file that was just in the current directory but this is still not working on my end; the file is not appearing in the students comment in the Speedgrader. Do you have any idea what could be going on? How are you using this method?

**Comment by jessemcbride** [comment]
Hey @sigurdurb, sorry for the late response.

The file is uploading correctly but it looks like there's another part of the submission comment process that requires linking the uploaded file to the submission. 

Per the [Canvas documentation](https://canvas.instructure.com/doc/api/submission_comments.html):

> The final step of the file upload workflow will return the attachment data, including the new file id. The caller can then PUT the file_id to the submission API to attach it to a comment.

Technically, it should be possible to link that the file through [Course.update_submission()](https://canvasapi.readthedocs.io/en/latest/course-ref.html#canvasapi.course.Course.update_submission) but we've discovered an issue with that.

We're working to resolve it and should have a fix soon.

Sorry about the inconvenience.

**Comment by Thetwam** [comment]
Hey @sigurdurb I think we have the solution to your problem! As @jessemcbride described above, the upload function works but to complete the process you need to attach the file via `Course.update_submission()`.

We found an issue with the `update_submission` method that prevented this attachment from working properly. We have since fixed it in #141.

With both the upload and update methods fixed, attaching is now possible!

```python
canvas = Canvas(API_URL, API_KEY)

course = canvas.get_course(COURSE_ID)
submission = course.get_submission(ASSIGNMENT_ID, USER_ID)
uploaded_file = submission.upload_comment(FILE_PATH)[1]
file_id = uploaded_file['id']
response = course.update_submission(
    ASSIGNMENT_ID,
    USER_ID,
    comment={
        'file_ids': [file_id]
    }
)
```

The above works, but it's not the most intuitive. To improve this process, we will investigate having the `upload_comment` method automatically link the file to the submission. I will open a separate issue for this.

Additionally, the `update_submission` method may change in the future, depending on how we handle #57. Keep an eye on the release notes of future patches for deprecation warnings.

**Comment by Thetwam** [comment]
New issue: #142

**Comment by sigurdurb** [comment]
For those who need this you can run 
`pip3 install -e git://github.com/ucfopen/canvasapi.git@develop#egg=canvasapi`
to get the latest from the developing branch.

**Comment by jessemcbride** [comment]
Hey @sigurdurb, you can actually grab this out of our latest release at v0.8.2. It includes some other bug fixes to make CanvasAPI a little more resilient, too.

Thanks again for reporting this :)

**Comment by sigurdurb** [comment]
Now uploading file on a submission comment is all in one function: 
Details #148 
Its in canvasapi version 0.9.0 #160
