### ISSUE TITLE
Course sections coverage

### ISSUE THREAD

**Issue by andrew-gardener** [ucfopen/canvasapi#154]
Add coverage for course sections

https://canvas.instructure.com/doc/api/sections.html#method.sections.index

Also improve course section coverage to support the `include` parameter

https://canvas.instructure.com/doc/api/sections.html#method.sections.show

**Comment by Thetwam** [comment]
I made some comments on the PR already (#155), but will duplicate some info here:

Getting multiple sections in a course is already covered as `Course.list_sections()` (See my comments on PR #155 and issue #156 for commentary on method naming schemes).
