### ISSUE TITLE
User Observees Endpoint

### ISSUE THREAD

**Issue by tuanvpham** [ucfopen/canvasapi#16]
https://canvas.instructure.com/doc/api/user_observees.html#method.user_observees.index
https://canvas.instructure.com/doc/api/user_observees.html#method.user_observees.create
https://canvas.instructure.com/doc/api/user_observees.html#method.user_observees.show
https://canvas.instructure.com/doc/api/user_observees.html#method.user_observees.update
https://canvas.instructure.com/doc/api/user_observees.html#method.user_observees.destroy

**Comment by Thetwam** [comment]
Resolved in #21
