### ISSUE TITLE
Get User Enrollments

### ISSUE THREAD

**Issue by ssilverm** [ucfopen/canvasapi#167]
Getting user enrollments requires a call to get the user (which pulls their profile info).  User enrollments and User profile use two different access roles.  An admin CAN'T pull the user profile of another admin, but CAN pull the enrollments of that admin.

user = canvas.get_user(user_id)
courses = user.get_courses(enrollment_type='Teacher', include=['sections'])

It would be great if I can setup a fake user object with the user id so that I can then reference the enrollments.

**Comment by jessemcbride** [comment]
Hi @ssilverm,

You can create fake objects as long as you're careful with how you use them.

In this case, you'd want something like this:
```
from canvasapi import Canvas
from canvasapi.user import User

canvas = Canvas(..., ...)

user = User(canvas._Canvas__requester, {'id': user_id})
user.get_courses(enrollment_type='Teacher', include=['sections'])
```

We've been working on lazy loading objects in #140 which should hopefully solve this problem in a library-supported way once it's complete.
