### ISSUE TITLE
Wrap “Grade or comment on multiple submissions” methods

### ISSUE THREAD

**Issue by liblit** [ucfopen/canvasapi#169]
The Canvas REST API offers [a suite of "Grade or comment on multiple submissions" methods](https://canvas.instructure.com/doc/api/submissions.html#method.submissions_api.bulk_update) that `canvasapi` 0.9.0 does not yet wrap. I recently had cause to use one of these methods, so proper `canvasapi` versions would be appreciated.

In my particular case I need to update grades for multiple assignments by multiple students. That presumably makes the `POST /api/v1/courses/:course_id/submissions/update_grades` entry point the right thing to use, although it is not clear to me whether one can indeed update multiple assignments for multiple students all in a single call.

**Comment by mboldin** [comment]
Under Documentation examples https://github.com/ucfopen/canvasapi/issues/147
I posted code to update a single grade using the submission.edit() method. I just loop through students for an assignment and call code the edit(posted_grade= <grade>)  for each one.  However allowing one to use a file of students and grades like the web interface allows makes sense as a new canvasapi feature.
