### ISSUE TITLE
Is it possible to get the current grades from enrollments for a course?

### ISSUE THREAD

**Issue by purpleHey** [ucfopen/canvasapi#178]
I tried getting the grades from enrollments aka:

`enrollments = course.get_enrollments(type=['StudentEnrollment'])`

But when I try to access grades they all show "None"?  Reading the API docs for Enrollments it states:

>  "grades": null,
>  // optional: The student's score in the course, ignoring ungraded assignments.
>  // (applies only to student enrollments, and only available in course endpoints)

Is that what the issue is?  Is there a way to get current grades using canvasapi?

**Comment by jessemcbride** [comment]
When I try to make this call through Postman using a course endpoint, I get back `StudentEnrollment` objects like this:

```
        // some other fields
        "grades": {
            "html_url": "https://webcourses.ucf.edu/courses/1263320/grades/3889181",
            "current_score": null,
            "current_grade": null,
            "final_score": null,
            "final_grade": null,
            "unposted_current_score": null,
            "unposted_current_grade": null,
            "unposted_final_score": null,
            "unposted_final_grade": null
        },
```
I don't think that information is missing because of a problem with the library, but rather because Canvas's documentation is incomplete (or incorrect) on grabbing that field. I'll pop in their IRC and see if I can get a more definite answer.

Sorry about the inconvenience.

**Comment by jessemcbride** [comment]
We resolved this over Slack.

In summary, Canvas treats assignments in a group with a 0% weight (if weighted grading is enabled) and assignments with zero possible points as non-existent. In this case, both were true, causing the grade-related fields to be `null`. You can fix this by ensuring that your assignments are in groups that are weighted properly (> 0%) or by making sure that your assignments have > 0 possible points.
