### ISSUE TITLE
Warn users that POST requests sent over non-HTTPS may fail

### ISSUE THREAD

**Issue by jessemcbride** [ucfopen/canvasapi#183]
In some cases, Canvas's API responds unpredictably when sending POST requests over HTTP instead of HTTPS.

For example, the `account.create_course` call will return the `GET` response if made over HTTP instead of HTTPS. This breaks `CanvasObject`'s attempts to automatically create an object:

```
>>> a.create_course(course={'name': 'JSA_TST1337_Jesse_McBride'})
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/canvasapi/account.py", line 77, in create_course
    return Course(self._requester, response.json())
  File "/usr/local/lib/python2.7/site-packages/canvasapi/canvas_object.py", line 28, in __init__
    self.set_attributes(attributes)
  File "/usr/local/lib/python2.7/site-packages/canvasapi/canvas_object.py", line 68, in set_attributes
    for attribute, value in attributes.items():
AttributeError: 'list' object has no attribute 'items'
```

It seems wrong to stop users at every POST call if they've set their `CANVAS_URL` to `http://*`. Instead, I think we should hook into `Requester._post_request` and raise a warning that the API call may not succeed.

**Comment by Thetwam** [comment]
What about cases where someone is running Canvas on a local development server that isn't using HTTPS? Those warnings would drive me mad.

**Comment by jessemcbride** [comment]
A reason to implement something like this resurfaced on our Slack channel, where Canvas returned an unexpected response with a paginated list when running over HTTP vs HTTPs. I agree that sending a warning on _every_ POST request might be too noisy, so I'll restrict it to only fire on instantiation of the Canvas object.
