### ISSUE TITLE
Submissions

### ISSUE THREAD

**Issue by nathaned** [ucfopen/canvasapi#20]
Add coverage for Submissions

https://canvas.instructure.com/doc/api/submissions.html#method.submissions.create
https://canvas.instructure.com/doc/api/submissions.html#method.submissions_api.index
https://canvas.instructure.com/doc/api/submissions.html#method.submissions_api.for_students
https://canvas.instructure.com/doc/api/submissions.html#method.submissions_api.show
https://canvas.instructure.com/doc/api/submissions.html#method.submissions_api.update
https://canvas.instructure.com/doc/api/submissions.html#method.submissions_api.gradeable_students
https://canvas.instructure.com/doc/api/submissions.html#method.submissions_api.mark_submission_read
https://canvas.instructure.com/doc/api/submissions.html#method.submissions_api.mark_submission_unread

**Comment by Thetwam** [comment]
Fixed in #24
