### ISSUE TITLE
Clean JSON responses at the requester level

### ISSUE THREAD

**Issue by jessemcbride** [ucfopen/canvasapi#202]
Previously, we noticed `while(1);` prepended to a response during the file upload process. This breaks requests's `Response.to_json()` method because technically an object of the form `while(1);{"key": "value"}` isn't valid JSON.

We resolved the issue by stripping `while(1);` out of the response at that stage in the uploader, but we didn't modify the rest of the codebase, thinking we wouldn't encounter it again. Today, I noticed `while(1);` prepended to a 401 response.

Rather than patching it in specific locations, it's probably a better idea to sanitize the response body directly before it leaves `Requester.request()`.

**Comment by jessemcbride** [comment]
I read a Canvas Community post last night about this where they mentioned specifying the `Content-Type` header as `application/json` forces Canvas to return valid JSON without the anti-JSON hijacking prefix.

I'd be curious to see if explicitly defining that resolves this issue. We might be able to remove the temporary fix in `Uploader` if it does.

**Comment by Thetwam** [comment]
Perhaps I'm misunderstanding, but I was under the impression that the `Content-Type` header specifies the type of content that you're sending, no the type that you're expecting to receive. We're still sending content as form data.

Do you know if Canvas respects `Accept` headers?

**Comment by jessemcbride** [comment]
You're right that it is formdata no matter what (and about Content-Type's actual purpose).

I wish I could find the forum post where they mentioned it. It was an offhand comment that definitely could have been incorrect. In any case, we may want to experiment with the request headers we're sending to see if we can tell Canvas explicitly that we want valid JSON.

**Comment by namanbiyani** [comment]
Hi i am interested in resolving this bug . Could you please indicate where the error might be and give some guidelines ?

**Comment by Thetwam** [comment]
@jessemcbride It's been a year since our last update.

Have we seen this behavior recently? Do we have a way of replicating? Is this worth pursuing?
