### ISSUE TITLE
Missing method to create section?

### ISSUE THREAD

**Issue by Mike-Nahmias** [ucfopen/canvasapi#204]
Version: 0.10.0
Python version: 3.7

Unless I missed it, I don't see a method to create a section. Please let me know if this is a desired addition and I'd be glad to submit a pull request.

**Comment by jessemcbride** [comment]
Course sections can be created with a course object through [Course.create_course_section()](https://canvasapi.readthedocs.io/en/latest/course-ref.html?#canvasapi.course.Course.create_course_section).

**Comment by Mike-Nahmias** [comment]
Thanks, still getting used to how things are organized.

**Comment by jonathan-taylor** [comment]
Trying to add a section with a specific name but name argument seems to be ignored...
```
In [39]: session = course.create_course_section(name='foo')
s
In [40]: session.name
Out[40]: 'Sandbox Course for Jonathan Taylor 2024-05-29'

In [41]: session
Out[41]: Section(_requester=<canvasapi.requester.Requester object at 0x105f8e110>, id=237377, course_id=187177, name=Sandbox Course for Jonathan Taylor 2024-05-29, start_at=None, end_at=None, created_at=2024-05-29T22:19:26Z, created_at_date=2024-05-29 22:19:26+00:00, restrict_enrollments_to_section_dates=None, nonxlist_course_id=None, sis_section_id=None, sis_course_id=None, integration_id=Non
```

**Comment by jonathan-taylor** [comment]
Solved this after checking CANVAS API.
