### ISSUE TITLE
Params not getting passed through on POSTs for Course methods

### ISSUE THREAD

**Issue by Mike-Nahmias** [ucfopen/canvasapi#205]
Version: 0.10.0
Python version: 3.7

I'm having issues with methods for Course where the params I'm sending as **kwargs aren't getting processed by Canvas. I believe I'm making the requests correctly, but if not please let me know. So far I'm having problems with:
course.create_course_section()
course.create_discussion_topic() 
course.create_assignment_group()

As far as I can tell, I'm only having problems for methods where the only param is **kwargs.

Example for create_course_section():
```
course = canvas.get_course(957)
course.create_course_section(
    section={
        'course_section[name]': 'Fall 2018 Term 1',
        'course_section[sis_section_id]': 'FL18T1'}
)
```
This results in a generic section getting created with none of the options I'm setting.

Example for create_discussion_topic():
```
course = canvas.get_course(957)
course.create_discussion_topic(
    discussion={
        'title': 'test discussion',
        'message': 'do stuff'
})
```
This results in a generic discussion getting created with none of the options I'm setting.

Example for create_assignment_group():
```
course = canvas.get_course(957)
course.create_assignment_group(
    group={
        'name': 'test group',
        'sis_source_id': 'test_group'
})
```
This results in a generic assignment group getting created with none of the options I'm setting.

I tried to update a course name using one of the pieces of sample code and that worked fine, but it's a PUT request. I haven't had any issues with POST methods that take params in addition to **kwargs, such as create_folder().

Any ideas?

**Comment by Thetwam** [comment]
Hey @Mike-Nahmias, looks like some formatting issues. I've included examples that should work below.

---

`create_course_section`:

```python
course.create_course_section(
    course_section={
        'name': 'Fall 2018 Term 1',
        'sis_section_id': 'FL18T1'
    }
)
```

---

`create_discussion_topic`:

```python
course.create_discussion_topic(title='test discussion', message='do stuff')
```

---

`create_assignment_group`:

```python
course.create_assignment_group(name='test group', sis_source_id='test_group')
```

---

In general, you can just pass things in as keyword arguments. The only time you need to pass in a dictionary is when things are nested.

The `create_course_section` method is a good example. The [Canvas docs for Create Course Section](https://canvas.instructure.com/doc/api/sections.html#method.sections.create) list several parameters . One of those parameters is `enable_sis_reactivation`, a boolean. To use this parameter, just pass it in as a keyword argument:

```python
create_course_section(enable_sis_reactivation=True)
```

The other parameters all look something like `course_section[foo]`. However, square brackets aren't a valid character for python variables, so the following wouldn't work:

```python
# This isn't valid, and won't work.
create_course_section(course_section[name]='New Section')
```

What Canvas is effectively doing with the bracket format is grouping things into objects. To get a similar effect in Python, we've set up CanvasAPI to handle it with dicts. The proper way to do this in CanvasAPI is like this:

```python
create_course_section(course_section={'name': 'New Section'})
```

In the background, CanvasAPI will combine the keys of the dictionary with the keyword of the argument, and ultimately send the correct variable to Canvas.

The benefit of this setup is that multiple parameters with the same prefix can be sent to the same keyword argument. So to pass the `course_section[name]`, `course_section[sis_section_id]`, and `course_section[integration_id]` arguments, it would look like this:

```python
create_course_section(
    course_section={
        'name': 'New Section',
        'sis_section_id': '123',
        'integration_id': '456'
    }
)
```

And to bring it all together, to pass several `course_section[foo]` arguments and `enable_sis_reactivation`, it would look like this:

```python
create_course_section(
    course_section={
        'name': 'New Section',
        'sis_section_id': '123',
        'integration_id': '456'
    },
    enable_sis_reactivation=True
)
```

---

Hopefully that explanation made sense. I'm happy to answer any other questions you might have! If you'd like to chat with us more directly, feel free to join us on the [UCF Open Source Slack Channel](https://ucf-open-slackin.herokuapp.com/) 😄

**Comment by Mike-Nahmias** [comment]
@Thetwam Thanks a lot for the quick and detailed response. That makes perfect sense, didn't think to try that. I adjusted the formatting and it is working perfectly.
