### ISSUE TITLE
Issues with Reports coverage and functionality

### ISSUE THREAD

**Issue by Mike-Nahmias** [ucfopen/canvasapi#206]
Version: 0.10.0
Python version: 3.7

**1) Available Account Reports do not have IDs in Canvas**

In Canvas, the list of available reports do not have IDs. 

An available report has these fields: report, title, parameters
A report has these fields: id, report, file_url, attachment, status, created_at, started_at, ended_at, parameters, progress, current_line

In Account.py I see that there is a class for AccountReport. I wonder if there should be a class for AccountReport and another class called AvailableAccountReport or something similar? And then get_reports() would return a PaginatedList of type AvailableAccountReport.

I noticed this when doing the following:
```
reports = account.get_reports()

for report in reports:
    print(report)
```
The above code gave me this error:
```AttributeError: 'AccountReport' object has no attribute 'id'```
This is my workaround:
```
reports = account.get_reports()

for report in reports:
    print(report.attributes)
```

**2) Unless I missed it, the wrapper is missing most Report methods** 
I need functionality to start a report and get the status of a report. It looks like this isn't supported in the wrapper? 

Let me know what you think and I can create a fork with some fixes if you'd like.

**Comment by jessemcbride** [comment]
Hey Mike, I just went down a rabbit hole looking through this and it looks like Canvas is sending us data that doesn't exactly add up with their documentation.

It looks like reports are used in two different contexts. In one, they're like a report template, where you have some default settings and a name and an ID and things like that. In another, they're used to represent an instance of a running (or previously ran) report, which has unique runtime settings and a name and an ID. The issue with `get_reports()` seems to be that they're returning a weird mix of those two types, where `report.last_run` has all of the information you'd need, but `report.id` is inexplicably missing.

So, with regards to the first point, we'll need to rework that method to return data correctly. We'll have to ask Instructure what's up with that, though... I'm not sure if we should just return a list of `dict`s or a new type all together. I'm going to hop in their IRC channel and see if I can get a clearer explanation about how these endpoints are supposed to function.

As for the observation about report methods missing, we'd be happy to get those endpoints covered and I think you can safely start working on that PR.

Sorry about the inconvenience. Let's leave this open so I can document what I learn once I talk to the Canvas devs.

**Comment by Mike-Nahmias** [comment]
Hey Jesse, yea the documentation on Instructure's site is a little confusing about this. They don't list a separate object type to describe what is returned from 'List Available Reports'. What I see on the API docs and our live API site differs in regards to the data that's returned. It looks like List Available Reports returns the available 'templates' with no IDs and Index of Reports returns actual Report objects.

I'll get started on a PR for the report methods. Thanks
