### ISSUE TITLE
Authentication Providers

### ISSUE THREAD

**Issue by tuanvpham** [ucfopen/canvasapi#22]
https://canvas.instructure.com/doc/api/authentication_providers.html#method.account_authorization_configs.index
https://canvas.instructure.com/doc/api/authentication_providers.html#method.account_authorization_configs.create
https://canvas.instructure.com/doc/api/authentication_providers.html#method.account_authorization_configs.update
https://canvas.instructure.com/doc/api/authentication_providers.html#method.account_authorization_configs.show
https://canvas.instructure.com/doc/api/authentication_providers.html#method.account_authorization_configs.destroy
https://canvas.instructure.com/doc/api/authentication_providers.html#method.account_authorization_configs.show_sso_settings
https://canvas.instructure.com/doc/api/authentication_providers.html#method.account_authorization_configs.update_sso_settings

**Comment by Thetwam** [comment]
Resolved in #31
