### ISSUE TITLE
Add support for SIS imports

### ISSUE THREAD

**Issue by nottheswimmer** [ucfopen/canvasapi#221]
API: https://canvas.instructure.com/doc/api/sis_imports.html

We should have support for handling SIS imports through this API. At minimum, basic support should support the APIs which enable the following (and allow arbitrary parameters/keyword arguments to be passed to them as well):
- Post files to the sis_imports API (CSV, XML, ZIP -- but for the wrapper the filetypes should be arbitrary)
- Get the status of sis_import workflows by account ID and unique identifier
- Get all imports
- Get all currently importing imports
- Restore workflow_states of SIS imported items
- Abort a specific SIS import
- Abort all pending SIS imports

Additionally, it would be nice of the SisImport object had the following methods, or similar:
- `SisImport.update` - Updates the SisImport object
- `SisImport.abort` - Aborts and updates the SisImport object
- `SisImport.restore_states` - Restore workflow_states of SIS imported items and returns Progress object.

Rough example of desired functionality:
```python
# POST /api/v1/accounts/:account_id/sis_imports
# Post .zip file to sis imports API with account ID 1 and the keyword argument to skip deletes
>>> with open('integrations.zip', 'rb') as data:
>>>     sis_import = canvas.create_sis_import(1, data, 'zip', skip_deletes=True)

# Accessing SisImport object properties
>>> sis_import.progress
0
>>> sis_import.id
2

# GET /api/v1/accounts/:account_id/sis_imports/:id
# Updating the sis_import object
>>> sis_import = canvas.get_sis_import(1, sis_import.id)
>>> sis_import.progress
10

# GET /api/v1/accounts/:account_id/sis_imports
>>> sis_imports = canvas.get_sis_imports(1)
>>> for x in sis_imports:
>>>     print(x.id)
1
2

# GET /api/v1/accounts/:account_id/sis_imports/importing
>>> sis_imports = canvas.get_sis_importing(1)
>>> for x in sis_imports:
>>>     print(x.id)
2

# PUT /api/v1/accounts/:account_id/sis_imports/:id/restore_states
>>> progress = canvas.sis_restore_states(1, 1)
>>> progress.completion
10
>>> progress = canvas.get_progress(progress)
>>> progress.completion
20

# PUT /api/v1/accounts/:account_id/sis_imports/:id/abort
>>> sis_import = canvas.abort_sis_import(1, sis_import.id)
>>> sis_import.workflow_state
'aborted'

# PUT /api/v1/accounts/:account_id/sis_imports/abort_all_pending
>>> with open('students.csv', 'rb') as students:
>>>     sis_import = canvas.create_sis_import(1, students, 'csv')
>>> sis_import.workflow_state
'importing'
>>> canvas.abort_pending_sis_imports()
>>> sis_import = canvas.get_sis_import(1, sis_import.id)
>>> sis_import.workflow_state
'aborted'
```

**Comment by Thetwam** [comment]
Resolved in #222
