### ISSUE TITLE
AssignmentGroups do not contain assignment IDs

### ISSUE THREAD

**Issue by foleyj2** [ucfopen/canvasapi#223]
When making an AssignmentGroup request, the returned object is missing the Assignment IDs.  Just to make sure that I wasn't confused, I did a REST query using insomnia and the JSON response contained the IDs as a list.  Why aren't they showing up here?

**Comment by Thetwam** [comment]
Hey @foleyj2,

Can I see the code you are making the call with in CanvasAPI, and the REST query you are making in insomnia for comparison?

In my local testing, I did not see a case where the assignment IDs were returned by default. However, by adding the parameter `include[]=assignments` to the REST query, the assignments would show up. This can be achieved in CanvasAPI by adding the parameter `include=['assignments']`.

For example, when using `get_assignment_groups`:

```python
course.get_assignment_groups(include=['assignments'])
```

**Comment by Thetwam** [comment]
Hey @foleyj2,

Since there hasn't been any activity on this issue in several months, I'm closing it. If you're still having this problem, please feel free to reopen the issue.

If you have any other questions, please feel free to make a new issue. Thanks!
