### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by tuanvpham** [ucfopen/canvasapi#23]
https://canvas.instructure.com/doc/api/analytics.html#method.analytics_api.department_participation
https://canvas.instructure.com/doc/api/analytics.html#method.analytics_api.department_grades
https://canvas.instructure.com/doc/api/analytics.html#method.analytics_api.department_statistics
https://canvas.instructure.com/doc/api/analytics.html#method.analytics_api.course_participation
https://canvas.instructure.com/doc/api/analytics.html#method.analytics_api.course_assignments
https://canvas.instructure.com/doc/api/analytics.html#method.analytics_api.course_student_summaries
https://canvas.instructure.com/doc/api/analytics.html#method.analytics_api.student_in_course_participation
https://canvas.instructure.com/doc/api/analytics.html#method.analytics_api.student_in_course_assignments
https://canvas.instructure.com/doc/api/analytics.html#method.analytics_api.student_in_course_messaging

**Comment by Thetwam** [comment]
Resolved in #30
