### ISSUE TITLE
edit() method for calendar events returns "calendar_event is missing" error

### ISSUE THREAD

**Issue by joonro** [ucfopen/canvasapi#239]
**Describe the bug**
When I try to edit a calendar event that I received with `user.get_calendar_events_for_user()`, I get `BadRequest: {"errors":[{"message":"calendar_event is missing"}]}` error. 

**To Reproduce**

```python
events = user.get_calendar_events_for_user(
    start_date='2019-08-25',
    end_date='2019-12-20',
)

for event in events:
    event.edit(
        event={
            'title': "New Title",
        })
```

Then I get:

```python
---------------------------------------------------------------------------
BadRequest                                Traceback (most recent call last)
<ipython-input-238-48a664d87a1c> in <module>()
----> 1 event.edit()

~\Anaconda3\lib\site-packages\canvasapi\calendar_event.py in edit(self, **kwargs)
     38             'PUT',
     39             'calendar_events/{}'.format(self.id),
---> 40             _kwargs=combine_kwargs(**kwargs)
     41         )
     42 

~\Anaconda3\lib\site-packages\canvasapi\requester.py in request(self, method, endpoint, headers, use_auth, _url, _kwargs, **kwargs)
     98         # Raise for status codes
     99         if response.status_code == 400:
--> 100             raise BadRequest(response.text)
    101         elif response.status_code == 401:
    102             if 'WWW-Authenticate' in response.headers:

BadRequest: {"errors":[{"message":"calendar_event is missing"}]}
```

**Expected behavior**
The event gets updated.

**Environment information (please complete the following information):**
- Python version (`python --version`)

    ```
    > python --version
    Python 3.6.3 :: Anaconda custom (64-bit)
    ```

- CanvasAPI version (`pip show canvasapi`)

```
> pip show canvasapi
Name: canvasapi
Version: 0.12.0
Summary: API wrapper for the Canvas LMS
Home-page: https://github.com/ucfopen/canvasapi
Author: University of Central Florida - Center for Distributed Learning
Author-email: techrangers@ucf.edu
License: MIT License
Location: c:\users\joon\anaconda3\lib\site-packages
Requires: requests, pytz, six
Required-by:
```

**Additional context**

**Comment by jessemcbride** [comment]
Hey @joonro,

It looks like the API is behaving normally in this case. If you take a look at the Canvas API docs for [Updating a calendar event](https://canvas.instructure.com/doc/api/calendar_events.html#method.calendar_events_api.update), an object with the name `calendar_event` is required.

In your code, you create a dict with the keyword argument `event`:
```
event.edit(
  event={
     'title': "New Title",
   })
```

Fortunately, all you need to do is rename the kwarg to `calendar_event` and you should see the behavior you expect. If you'd like to get some more context on how CanvasAPI processes keyword arguments for API calls, check out our [Keyword Arguments](https://canvasapi.readthedocs.io/en/latest/keyword-args.html) docs.

Let me know if that resolves your issue. If it doesn't, the API is behaving unpredictably, and we can do some additional troubleshooting. Thanks!

**Comment by joonro** [comment]
It worked perfectly after I changed `event` kwarg to `calendar_event` as you suggested. Thank you very much for your quick reply.

This is not obvious to a new user, so it would be great if it can be included as an example - can I add one and open a PR?

**Comment by Thetwam** [comment]
Glad it worked!

We would very much appreciate a pull request with an example 😄

**Comment by jessemcbride** [comment]
I've added this to our catch-all documentation examples issue. Feel free to submit a PR when you have the time!
