### ISSUE TITLE
Blank Canvas URL Warning

### ISSUE THREAD

**Issue by gdijkhoffz** [ucfopen/canvasapi#240]
If a Canvas instance is created with a blank URL field:

```
canvas = Canvas(' ', 'KEY')
user = canvas.get_user('id')
```
All calls that are made with a blank URL will receive this error:

`raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'url/path'`

This error isn't very helpful for identifying the issue at hand, so I thought it'd be better to add an exception when a call is made with a blank URL field that says you cannot have a blank URL.

**Comment by Thetwam** [comment]
Hey @gdijkhoffz, thanks for the bug report and feature request.

The example you provided throws a different exception for me:

```
TypeError: Parameter user must be of type User or int.
```

When I replace `'id'` with `1`, I get a different (though similar) exception to the one you reported:

```
requests.exceptions.MissingSchema: Invalid URL '/api/v1/users/1': No schema supplied. Perhaps you meant http:///api/v1/users/1?
```

The above exception is actually somewhat helpful, but I think you're right and we can do even better.

In addition to the issue happening with blank URLs, it will also happen with any value provided that doesn't contain a schema (HTTP/HTTPS). To resolve both this issue and the one you've reported, it's probably best to throw a warning if the user doesn't provide a valid schema when initializing the `Canvas` object.
