### ISSUE TITLE
File Upload Process Change

### ISSUE THREAD

**Issue by Thetwam** [ucfopen/canvasapi#269]
Investigate deprecation warning about 3rd step of file upload

https://canvas.instructure.com/doc/api/file.file_uploads.html

**Comment by jessemcbride** [comment]
Is this issue still relevant? I know our goal is to improve the upload code, but I believe Canvas has changed their docs, moving the deprecation warning elsewhere.

**Comment by Thetwam** [comment]
I honestly don't remember what the warning was 😅

**Comment by jessemcbride** [comment]
Heh, no worries. Going to close this. Let's revisit it if it comes up again. 👍
