### ISSUE TITLE
quiz.get_all_quiz_submissions() Does not process all pages

### ISSUE THREAD

**Issue by Mike-Nahmias** [ucfopen/canvasapi#270]
# Describe the bug

quiz.get_all_quiz_submissions() only returns 10 submissions and does not handle multiple pages.

# To Reproduce

1) Create canvasapi client
2) Get a course
3) Get a quiz in that course that has more than 10 submissions
4) Call quiz.get_all_quiz_submissions() and you'll find that only 10 were returned

# Expected behavior

The page_size param should probably default to 100 and a pagination_list should be returned like other requests.

# Environment information (please complete the following information)

- Python version (`python --version`): 3.7.0
- CanvasAPI version (`pip show canvasapi`): 0.12.0

# Additional context

If the quiz is also an assignment, then assignment.get_submissions() works fine. However, if a quiz does not offer points then it is not also an assignment and you need to use quiz.get_all_quiz_submissions()

**Comment by Thetwam** [comment]
Hey @Mike-Nahmias, thanks for the bug report.

I am able to replicate and think I see the issue. Will start working on a fix.
