### ISSUE TITLE
importing ABCs from collections will be deprecated in Python 3.8

### ISSUE THREAD

**Issue by Screeeech** [ucfopen/canvasapi#284]
I get this warning every time I import canvasapi:
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

**Comment by Thetwam** [comment]
CanvasAPI does not directly use `collections.abc`, so this is probably coming from a dependency.

What versions of the dependencies do you have installed? (`pip list`)

**Comment by Screeeech** [comment]
The one in question would be google-api-python-client.
Here is something strange that I noticed with it:

There is no warning when I call the google Calendar API by itself, there is no warning when I call the canvas API by itself, but there is a warning when I call the google Calendar API and import canvasapi

**Comment by Thetwam** [comment]
It's definitely possible that `google-api-python-client` is the culprit, or one of its dependencies, but `canvasapi` does not use `collections.abc`.

The best suggestion I have is to make sure `canvasapi` and its dependencies are fully up to date by running:

```
pip install --upgrade canvasapi requests pytz
```

If that doesn't solve your issue, it lies elsewhere.

**Comment by jessemcbride** [comment]
Hey @Screeeech, that does sound like a strange issue. I did a little bit of digging and I understand what's going on now:

`google-api-python-client` has a dependency library called [uritemplate](https://uritemplate.readthedocs.io/en/latest/). uritemplate has a method called `dict_test` that references a collections object directly (i.e. not using `collections.abc`): 

```
def dict_test(value):
    print(value)
    return isinstance(value, (dict, collections.MutableMapping))
```

This type of access is going to be phased out in Python 3.8, per the DeprecationWarning:

> DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

So, that's good, we know where the DeprecationWarning is coming from. But why does it only get displayed when you use CanvasAPI?

It's true that CanvasAPI doesn't make use of `collections` in a direct way that would trigger this DeprecationWarning. It does, however, also use DeprecationWarnings internally to warn our users about endpoints that are going away or modified client behavior, and in [canvasapi/canvas.py](https://github.com/ucfopen/canvasapi/blob/develop/canvasapi/canvas.py#L20), we explicitly enable DeprecationWarnings:

```
from canvasapi.util import combine_kwargs, get_institution_url, obj_or_id


warnings.simplefilter("always", DeprecationWarning)


class Canvas(object):
    """
    The main class to be instantiated to provide access to Canvas's API.
    """
    ...
```

This is probably overzealous on our part and it would explain why importing CanvasAPI also reveals the behavior raising the DeprecationWarning in `uritemplate/variable.py`. I'm not sure why we opted to explicitly raise the warnings, but we may want to revisit that decision to prevent conflicts like this from occurring in the future. In the meantime, you can always suppress warnings by making a call to the `warnings` module by yourself or by passing the `-W` flag to Python (e.g. `python -W ignore::DeprecationWarning`).

**Comment by Screeeech** [comment]
That explains it... I was trying out so many things to try to get that warning to go away. Also, thanks for pointing out that it came from uritemplate. Turns out that the newest version of uritempate on GitHub adresses this, so I'm passing this issue onto gsuitedevs/python-samples to alert them of this problem with a link to this discussion

**Comment by Thetwam** [comment]
Decided after [further reading](https://docs.python.org/3/library/warnings.html#updating-code-for-new-versions-of-dependencies) to not turn on `DeprecationWarning` by default.

See PR #285.

**Comment by Thetwam** [comment]
Looks like there was more to this one than we originally thought. In `util.py` we call `from collections import Iterable`, and use it in the `is_multivalued` function:

```python
# general rule: multivalued if iterable
return isinstance(value, Iterable)
```

This might be what is triggering these warnings.

We could switch to [importing `Iterable` from `typing`](https://docs.python.org/3/library/typing.html#typing.Iterable), although according to the [docs for `Iterable`](https://docs.python.org/3/library/collections.abc.html#collections.abc.Iterable):

> The only reliable way to determine whether an object is iterable is to call iter(obj).

Calling `iter()` does make make the code a little less pretty, but may be more robust. Regardless of what path we take, we'll need to move away from importing `Iterable` from collections.
