### ISSUE TITLE
Custom Gradebook Columns

### ISSUE THREAD

**Issue by Thetwam** [ucfopen/canvasapi#295]
**What resource needs additional coverage?**

Custom Gradebook Columns

**What endpoints need to be covered?**

https://canvas.instructure.com/doc/api/custom_gradebook_columns.html

Custom Gradebook Columns:
- [ ] List custom gradebook columns
- [ ] Create a custom gradebook column
- [ ] Update a custom gradebook column
- [ ] Delete a custom gradebook column
- [ ] Reorder custom columns

Custom Gradebook Column Data:
- [ ] List entries for a column
- [ ] Update column data
- [ ] Bulk update column data

**Comment by hudcap** [comment]
Are there any updates on this?

**Comment by Thetwam** [comment]
Hey @hudcap, sorry we've been quiet on this one. We haven't gotten a chance to do much work on CanvasAPI over the last few months.

We intend to work on this endpoint for either the 0.16.0 milestone or the subsequent one. Unfortunately, I don't have a timeline for that at this time. I'll post in this issue again when we start work on it.

**Comment by Thetwam** [comment]
Hey @hudcap, We've identified that this issue will be addressed in CanvasAPI v1.1.0. Keep an eye on this issue for updates.

**Comment by hudcap** [comment]
Thank you for all your work on this amazing project!

**Comment by Thetwam** [comment]
Hey @hudcap, support for custom gradebook columns is now live in version 2.0.0

**Comment by hudcap** [comment]
Awesome! Thank you so much!
I already upgraded `canvasapi` and am in middle of playing with it right now :)
