### ISSUE TITLE
Usage Rights (Files)

### ISSUE THREAD

**Issue by joonro** [ucfopen/canvasapi#298]
I would like to set usage rights (published, etc) for specific files. It seems [Files API/set_usage_rights](https://canvas.instructure.com/doc/api/files.html#method.usage_rights.set_usage_rights) should do it, but I haven't been able to figure out how to do this with canvasapi. I'm sorry if this is already implemented!

**What resource needs additional coverage?**
Usage Rights

**What endpoint needs to be covered?**
https://canvas.instructure.com/doc/api/files.html
  - [ ] [Set usage rights](https://canvas.instructure.com/doc/api/files.html#method.usage_rights.set_usage_rights)
  - [ ] [Remove usage rights](https://canvas.instructure.com/doc/api/files.html#method.usage_rights.remove_usage_rights)
  - [ ] [List Licenses](https://canvas.instructure.com/doc/api/files.html#method.usage_rights.licenses)

_New to working on CanvasAPI? Check out our [contributing guide](https://github.com/ucfopen/canvasapi/blob/develop/.github/CONTRIBUTING.md)!_

**Comment by Thetwam** [comment]
Hey @joonro, I updated the issue so it will get more attention in the future. Thanks for submitting 😄

**Comment by atarisafari** [comment]
I'll work on this!
