### ISSUE TITLE
Endpoint coverage for updating external tools

### ISSUE THREAD

**Issue by altgilbers** [ucfopen/canvasapi#299]
**What resource needs additional coverage?**
Courses, Accounts, External Tools

**What endpoints need to be covered?**
https://canvas.instructure.com/doc/api/external_tools.html#method.external_tools.update

- PUT /api/v1/accounts/:account_id/external_tools/:external_tool_id
- PUT /api/v1/courses/:course_id/external_tools/:external_tool_id

**Comment by altgilbers** [comment]
I have this written... just need to tidy up before submitting pull request.

**Comment by Thetwam** [comment]
Hey @altgilbers,

I think we already have this covered as `ExternalTool.edit` in `external_tool.py`

**Comment by altgilbers** [comment]
doh..   I looked in the wrong spot...

I guess if the item being updated has it's own class, the updates are handled there...  make sense.

I was seeing other update methods in courses and accounts and expected to find one for external tools there as well.   I also was looking for update not edit...   :)

Thanks for pointing me in the right direction.
