### ISSUE TITLE
Assignment Extensions

### ISSUE THREAD

**Issue by Thetwam** [ucfopen/canvasapi#309]
**What resource needs additional coverage?**
Assignment Extensions

**What endpoint needs to be covered?**
https://canvas.instructure.com/doc/api/assignment_extensions.html#method.assignment_extensions.create
  - [ ] Set extensions for student assignment submissions

_New to working on CanvasAPI? Check out our [contributing guide](https://github.com/ucfopen/canvasapi/blob/develop/.github/CONTRIBUTING.md)!_

**Comment by ljoks** [comment]
i want to do this
