### ISSUE TITLE
Brand Configs

### ISSUE THREAD

**Issue by Thetwam** [ucfopen/canvasapi#311]
**What resource needs additional coverage?**
Brand Configs

**What endpoint needs to be covered?**
https://canvas.instructure.com/doc/api/brand_configs.html

- [ ] Get the brand config variables that should be used for this domain

_New to working on CanvasAPI? Check out our [contributing guide](https://github.com/ucfopen/canvasapi/blob/develop/.github/CONTRIBUTING.md)!_

**Comment by bennettscience** [comment]
I'll work on this.
