### ISSUE TITLE
CommMessages

### ISSUE THREAD

**Issue by Thetwam** [ucfopen/canvasapi#312]
**What resource needs additional coverage?**
CommMessages

**What endpoint needs to be covered?**
https://canvas.instructure.com/doc/api/comm_messages.html

- [ ] List of CommMessages for a user

_New to working on CanvasAPI? Check out our [contributing guide](https://github.com/ucfopen/canvasapi/blob/develop/.github/CONTRIBUTING.md)!_

**Comment by ljoks** [comment]
@ljoks
