### ISSUE TITLE
Grade Change Log

### ISSUE THREAD

**Issue by Thetwam** [ucfopen/canvasapi#322]
**What resource needs additional coverage?**
Grade Change Log

**What endpoint needs to be covered?**
https://canvas.instructure.com/doc/api/grade_change_log.html

  - [ ] Query by assignment
  - [ ] Query by course
  - [ ] Query by student
  - [ ] Query by grader

_New to working on CanvasAPI? Check out our [contributing guide](https://github.com/ucfopen/canvasapi/blob/develop/.github/CONTRIBUTING.md)!_

**Comment by ctcuff** [comment]
I'll take this one

**Comment by Thetwam** [comment]
As stated in #329:

This is blocked by #114 as this may require modification to PaginatedList's behavior.
