### ISSUE TITLE
Quiz Reports

### ISSUE THREAD

**Issue by Thetwam** [ucfopen/canvasapi#327]
**What resource needs additional coverage?**
Quiz Reports

**What endpoints need to be covered?**
https://canvas.instructure.com/doc/api/quiz_reports.html

- [ ] Retrieve all quiz reports
- [ ] Create a quiz report
- [ ] Get a quiz report
- [ ] Abort the generation of a report, or remove a previously generated one

_New to working on CanvasAPI? Check out our [contributing guide](https://github.com/ucfopen/canvasapi/blob/develop/.github/CONTRIBUTING.md)!_

**Comment by atarisafari** [comment]
I'll take care of this
