### ISSUE TITLE
Quiz Submission User List

### ISSUE THREAD

**Issue by Thetwam** [ucfopen/canvasapi#328]
**What resource needs additional coverage?**
Quiz Submission User List

**What endpoints need to be covered?**
https://canvas.instructure.com/doc/api/quiz_submission_user_list.html

- [ ] Send a message to unsubmitted or submitted users for the quiz

_New to working on CanvasAPI? Check out our [contributing guide](https://github.com/ucfopen/canvasapi/blob/develop/.github/CONTRIBUTING.md)!_

**Comment by gdijkhoffz** [comment]
Can I be assigned to this?

**Comment by Thetwam** [comment]
Resolved in #336
