### ISSUE TITLE
Can I use CanvasAPI as a student to check my grades?

### ISSUE THREAD

**Issue by enderzhangpro** [ucfopen/canvasapi#359]

**Comment by moorereason** [comment]
I haven't tested that using this package, but I'm assuming it will work. The Canvas API is open to any user.  Go to your Canvas profile settings, generate an API Key, and give it a try.

**Comment by Thetwam** [comment]
Hey @enderzhangpro, sorry for the long delay in response - things have been crazy lately.

You should absolutely be able to check your grades as a student with CanvasAPI! Grades are returned in the Enrollments endpoints.

First, as @moorereason said, you'll need to generate an API Key. You can create an access token by following the [instructions on this page under "Add Access Token"](https://community.canvaslms.com/docs/DOC-16005-42121018197).

Then, check out the [Quickstart section of the Readme](https://github.com/ucfopen/canvasapi#quickstart) or the [Usage section of our documentation](https://canvasapi.readthedocs.io/en/stable/getting-started.html#usage) to get your `Canvas` object initialized.

I've included more detailed code below, but here are the broad strokes:

1. Grab your user object
2. Use your user object to get enrollments
3. Access the grades dictionary inside each enrollment

```python
canvas = Canvas(API_URL, API_KEY)

# You can also get a user by id with canvas.get_user(),
# but you'll need elevated permissions to see other users
me = canvas.get_current_user()

# You can play around with the `type`, `state`, and other parameters to get different enrollments
my_enrollments = me.get_enrollments(type=["StudentEnrollment"], state=["active"])

for enrollment in my_enrollments:
    # The enrollments API only provides the course ID. For more info about the course,
    # you'll need to call canvas.get_course() and pass in the ID
    print(enrollment.course_id)

    # Grades is a dictionary with what you seek
    print(enrollment.grades)

    # You're probably most interested in current_score and current_grade
    print(enrollment.grades.get("current_score"))
    print(enrollment.grades.get("current_grade"))

    # Cleaned up print output
    print(
        "Course #{}: {} ({})".format(
            enrollment.course_id,
            enrollment.grades.get("current_score"),
            enrollment.grades.get("current_grade"),
        )
    )
```

---

Hopefully that answers your question! I'm going to close this issue, but if you have any further questions feel free to re-open it. You can also [join our UCF Open Source Slack](https://ucf-open-slackin.herokuapp.com/) and join the `#canvasapi` channel where lots of friendly and helpful people hang out.

**Comment by JayantDevkar** [comment]
hey @Thetwam. I am trying to make a virtual assistant that can help me see my grades and assignment due and other stuff easily on my command and to extract data I want to use Canvas API. 
So, I was able to create the Access key but I am not sure where to find API_URL.

**Comment by Thetwam** [comment]
@JayantDevkar `API_URL` is just the url of your institution's Canvas instance. It depends on how your institution has things set up, but it'll probably look something like `https://example.instructure.com` or `https://canvas.example.edu`.
