### ISSUE TITLE
Build documentation from master, not develop

### ISSUE THREAD

**Issue by jessemcbride** [ucfopen/canvasapi#366]
Currently our docs are built off of our develop branch and can occasionally include features that haven't been officially released yet. Updating our docs to build using the master branch instead of develop would resolve the discrepancy.

**Comment by Thetwam** [comment]
RTD builds from whatever the default branch is. In the case of canvasapi, the default branch is `develop`. Not sure what we can do about that.

**Comment by jessemcbride** [comment]
Closing in favor of #368
