### ISSUE TITLE
CurrentUser Documentation

### ISSUE THREAD

**Issue by Thetwam** [ucfopen/canvasapi#367]
The function `get_current_user` in `canvas.py` doesn't have an entry in our docs. I suspect this is because it doesn't have a docstring.

Additionally, it isn't obvious from our documentation that `CurrentUser` objects have all the methods of the `User` class.

- [ ] Add a docstring to `get_current_user`, including description and return type.
- [ ] Add text to `current-user-ref.rst` explaining that the `CurrentUser` class is a subclass of the `User` class, and thus inherits all of the methods of `User`.
- [ ] In the explanation above, provide a link to the `User` class reference page.

**Comment by Xx-Ashutosh-xX** [comment]
I think this would be a good first PR for me... so I would like to help with it.

**Comment by Thetwam** [comment]
@Xx-Ashutosh-xX Awesome, welcome aboard! Let us know if you have any questions 😁
