### ISSUE TITLE
Set up nightly builds

### ISSUE THREAD

**Issue by jessemcbride** [ucfopen/canvasapi#369]
Recently an update of a development dependency, flake8, caused our [develop branch's pipeline to start failing](https://travis-ci.org/ucfopen/canvasapi/builds/694292082).

Setting up nightly builds that attempt to install the latest version of canvasapi's dependencies would warn us about changes like this in the future.

**Comment by Thetwam** [comment]
Seems straightforward:

https://docs.travis-ci.com/user/cron-jobs/

Just need to keep this in mind:

> If your API or cron triggered builds run on the same commit or branch over and over again, you will notice GitHub have a limit of 1000 status updates per commit, which causes the Travis CI build status displayed on GitHub to be incorrect. Avoid this problem by specifying a regularly updated branch for your automated builds.

**Comment by Thetwam** [comment]
Should we do a nightly build of `master`, `develop` or both?

**Comment by jessemcbride** [comment]
I think building nightly on `develop` would be our best bet as it is updated most frequently.

**Comment by jonespm** [comment]
This is still failing, created #373 for this

**Comment by Thetwam** [comment]
Set up `develop` to build daily. At the moment, none of our requirements in `tests_requirements.txt` or `requirements.txt` have pinned version numbers, so this will always install the latest version of each of those packages each day.

If we eventually decide to pin requirements version for some reason, we'll want to look into adjusting the daily build to install the latest version of those packages(s)
