### ISSUE TITLE
try to loop through a PaginatedList of type Course but triggered AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by amorqiu** [ucfopen/canvasapi#370]
# Describe the bug
It seems when I try to loop through the `PaginatedList of type Course` and print it out, a traceback error will show up. Like this, see below

Traceback (most recent call last):
  File"C:\Users\qchen\Documents\ITS\Canvas_script\lti_report\generate_term.py", line 51, in <module>
    for i in courses:
File"C:\Users\qchen\AppData\Local\Programs\Python\Python37-32\lib\site packages\canvasapi\paginated_list.py", line 49, in __iter__
    new_elements = self._grow()
File"C:\Users\qchen\AppData\Local\Programs\Python\Python37-32\lib\site-packages\canvasapi\paginated_list.py", line 93, in _grow            
new_elements = self._get_next_page()
File"C:\Users\qchen\AppData\Local\Programs\Python\Python37-32\lib\site-packages\canvasapi\paginated_list.py", line 67, in _get_next_page
re.search(regex,next_link["url"]).group(1) if next_link else None
AttributeError: 'NoneType' object has no attribute 'group'

# To Reproduce

1. Go to 'command line'
2. Click on 'run my python script'
my code is like this:
`canvas = Canvas(API_URL, API_KEY)
account=canvas.get_account(147)
courses=account.get_courses(include=['term'])
for i in courses: 
    print(i.term)`

3. See error

# Expected behavior
I want to loop through my list of course and get term information.

# Environment information

- Python version (`python --version`): Python 3.7.2
- CanvasAPI version (`pip show canvasapi`): Version: 0.15.0

# Additional context
I can print out the account list but it doesn't work for the course list. After I changed my file for api link nd token, it worked. Then I compare the api link with my previous one, I found there is an extra whitespace at the beginning of my api url. It seems that's the reason why my code doesn't work.

**Comment by AnnapolisKen** [comment]
I'm finding the PaginatedList object very difficult to work with. I'm trying to get the last time a user logged in. The documentation says that this PaginatedList object works like a list. So my code is:
```
login_events = theUser.get_authentication_events()
logins=login_events[0]
```
The last line gives me a <class 'AttributeError'>

How do I access the authentication events?
Thanks!
