### ISSUE TITLE
How to access user's to-do list?

### ISSUE THREAD

**Issue by JayantDevkar** [ucfopen/canvasapi#374]
Can I access the to-do list of a user like the upcoming assignments?

**Comment by JayantDevkar** [comment]
hey @Thetwam  can you help?

**Comment by Thetwam** [comment]
Hey @JayantDevkar, you can get the to-do list of the current user by calling `canvas.get_todo_items()`

https://canvasapi.readthedocs.io/en/stable/canvas-ref.html#canvasapi.Canvas.get_todo_items
