### ISSUE TITLE
Files Resolve Path

### ISSUE THREAD

**Issue by Thetwam** [ucfopen/canvasapi#379]
#375 / #378 Added support for `GET /api/v1/courses/:course_id/folders/by_path/*full_path`, but there are several other related endpoints under the "Resolve Path" umbrella.

**What resource needs additional coverage?**
Files, Folders, "Resolve Path"

**What endpoints need to be covered?**

- [ ] `GET /api/v1/courses/:course_id/folders/by_path`
- [ ] `GET /api/v1/users/:user_id/folders/by_path/*full_path`
- [ ] `GET /api/v1/users/:user_id/folders/by_path`
- [ ] `GET /api/v1/groups/:group_id/folders/by_path/*full_path`
- [ ] `GET /api/v1/groups/:group_id/folders/by_path`

https://canvas.instructure.com/doc/api/files.html#method.folders.resolve_path

**Comment by dsavransky** [comment]
I'm happy to finish this one off since I started it.  Just to check - are you ok with effectively the same code being cloned between multiple classes when you're covering endpoints like these, or offloaded to a single method somewhere?

**Comment by Thetwam** [comment]
@dsavransky We're generally fine with similar code being in multiple classes, but if you have any ideas for a universal method, we'd be interested in seeing what you can come up with!
