### ISSUE TITLE
Improper API_URL Processing

### ISSUE THREAD

**Issue by Thetwam** [ucfopen/canvasapi#390]
# Describe the bug

v0.16.0 introduced a bug where the cleanup function `get_institution_url` is no longer altering the `base_url`.

# To Reproduce

1. Instantiate `Canvas` with an `API_URL` like `"https://example.com/api/v1/"`
2. Investigate the requester object for base url: `canvas._Canvas__requester.base_url`
3. Observe malformed url: `"https://example.com/api/v1//api/v1/"`

# Expected behavior

URL should be cleaned properly: `"https://example.com/api/v1/"`

# Environment information

- Python version (`python --version`) 3.8.3
- CanvasAPI version (`pip show canvasapi`) 0.16.0

# Additional context

Official support for trailing `/api/v1/` in the `API_URL` was deprecated in v0.8.0, and will be removed in v1.0.0.

**Comment by jessemcbride** [comment]
Heh, whoops. 😅

Good catch.
