### ISSUE TITLE
Update xenial to bionic for Travis

### ISSUE THREAD

**Issue by jonespm** [ucfopen/canvasapi#393]
# Describe the bug

The [.travis.yml](https://github.com/ucfopen/canvasapi/blob/develop/.travis.yml) currently uses xenial as a dist. [Travis supports bionic](https://docs.travis-ci.com/user/reference/bionic/) and with dropping Python 2 and earlier versions of 3.x in #385 this should also be updated to stay on the most recent releases of Python. 

This probably isn't a rush but there haven't been new releases for Xenial in over a year, even though it has standard support until early 2021.

**Comment by Thetwam** [comment]
@jonespm Good call 👍
