### ISSUE TITLE
Get older course ids (not in favorites)  

### ISSUE THREAD

**Issue by mboldin** [ucfopen/canvasapi#408]
# Describe the bug

canvas.get_courses()  seems to only get a list of course favorites, where canvas is my API connection as teacher 

Is there a way to get course id of all available courses ?

For courses where I know the id, and then I can access the course items

**Comment by moorereason** [comment]
Check the `state[]` parameter from [the Canvas API docs](https://canvas.instructure.com/doc/api/courses.html#method.courses.index).  Can you confirm the issue doesn't exist when using curl?

**Comment by Thetwam** [comment]
`Canvas.get_courses()` only returns the active courses for the current user (the user who owns the provided Access Token).

To get a broader list of the user's courses beyond active, you can include the `state` parameter, as @moorereason mentioned.

```python
canvas.get_courses(state=['unpublished', 'available', 'completed', 'deleted'])
```

If you want to see other courses besides those that belong to the user, you'll need to get them at the account level with [`Account.get_courses()`](https://canvasapi.readthedocs.io/en/stable/account-ref.html#canvasapi.account.Account.get_courses). I highly recommend using parameters to filter this search, as there are likely to be a LOT of courses returned from that call. This endpoint may have limited (or no) results, based on your permissions level.

To get an account, you can user [`Canvas.get_account()`](https://canvasapi.readthedocs.io/en/stable/canvas-ref.html#canvasapi.Canvas.get_account) if you know the Account ID, or look through [`Canvas.get_accounts()`](https://canvasapi.readthedocs.io/en/stable/canvas-ref.html#canvasapi.Canvas.get_accounts) to see what accounts are available to you. Again, this may be subject to restrictions based on your permission level in the LMS.
