### ISSUE TITLE
Download submission annotations and comments

### ISSUE THREAD

**Issue by marvic2409** [ucfopen/canvasapi#416]
**What resource needs additional coverage?**
e.g. Courses, Users, Accounts, Quizzes
Submission annotations and comments
**What endpoints need to be covered?**
Specify individual endpoints and provide a link to the endpoint in Canvas's API documentation
I am not sure if this endpoint exists, but I was wondering if it was possible to get the submission annotations (Which are downloadable when you click view feedback) and the comments.

**Comment by bennettscience** [comment]
There isn't a specific endpoint for comments, but you can request the comments with a [keyword argument](https://canvas.instructure.com/doc/api/submissions.html#method.submissions_api.show).

Using `Assignment.get_submission(include=submission_comments)`, you'll get the `Submission` object will include comment objects in a list.

```javascript
// Associated comments for a submission (optional)
  "submission_comments": null,
```

```javascript
{
  "id": 37,
  "author_id": 134,
  "author_name": "Toph Beifong",
  // Abbreviated user object UserDisplay (see users API).
  "author": "{}",
  "comment": "Well here's the thing...",
  "created_at": "2012-01-01T01:00:00Z",
  "edited_at": "2012-01-02T01:00:00Z",
  "media_comment": null
}
```

**Comment by michaelstepner** [comment]
I found the reply above from @bennettscience very helpful. I have two notes to add for others who are trying to download comments:

1. You'll need to `include="submission_comments"` (submission_comments is a string)
2. This also works with the `Assignment.get_submissions()` function.

So, for example, this code works to retrieve all submissions along with their comments:

```
assignment = course.get_assignment(assignment_id)
submissions = assignment.get_submissions(include="submission_comments")
```

**Comment by marvic2409** [comment]
Sorry for leaving it open, I kinda forgot about this.
