### ISSUE TITLE
Example for Course Creation?

### ISSUE THREAD

**Issue by jubilus** [ucfopen/canvasapi#418]
Greetings,

I'm trying to find the correct syntax for using this library to create courses. Does anyone have an example they would be willing to share?

[The documentation on the Canvas site is located here.](https://canvas.instructure.com/doc/api/courses.html#method.courses.create)

**Comment by jessemcbride** [comment]
Hi @jubilus, you can create a course like this:

```
# With some account (e.g. account id 1)
account = canvas.get_account(1)

# Call create_course using the keyword argument syntax
course = account.create_course(
    course={
        "name": "A course name",
        "course_code": "SOME-COURSE-CODE"
)
```

You can optionally pass more arguments (as the Canvas docs reveal). Take a peek at our [Keyword Arguments](https://canvasapi.readthedocs.io/en/stable/keyword-args.html#nested-parameters) docs (in particular, the "Nested Parameters" section) for more information about how to form these calls.

Let us know if you have any other questions -- feel free to pop into the #canvasapi channel on our [Slack team](https://ucf-open-slackin.herokuapp.com/).

**Comment by jubilus** [comment]
Thank you so much!
