### ISSUE TITLE
How to Retrieve Page Content

### ISSUE THREAD

**Issue by IreTheKID** [ucfopen/canvasapi#419]
### The Setup

I've written a few lines of code the get the page content from the front page of a course. I use a for loop to iterate over the PaginatedList and dump it into a new list for loading purposes (It's pretty redundant, but in my experience, it helps prevent `TypeError`s). The code looks like this:

```python3
course = canvas.get_course(123456)
p = course.get_pages()

pages = []
for i in range(100):
    try:
        pages.append(p[i])
    except IndexError:
        break

for page in pages:
    if page.front_page:
        print(f"~~{page.title}~~ \n{page.body}")
    else:
        pass
```

### The Problem

Upon running the code, I get this error: 

```python
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    print(f"~~{x.title}~~ \n{x.body}")
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/canvasapi/canvas_object.py", line 17, in __getattribute__
    return super(CanvasObject, self).__getattribute__(name)
AttributeError: 'Page' object has no attribute 'body'
```

I get an `AttributeError` saying that the *'Page' object has no attribute 'body'*. This is confusing because according to the  Canvas LMS docs says that the page content is contained in the "body" attribute. 'Page' object has no attribute 'body'
![image](https://user-images.githubusercontent.com/62220201/93253113-6aded480-f764-11ea-950e-26326890d89a.png)

Looking at the code for the `Page` object (i.e `CanvasObject`) leads me to believe that this might be an issue with the Canvas LMS API, but I'm honestly not too sure.

**`canvasapi/canvasapi/canvas_object.py`**
*`Lines: 16-18`*

```python3
    def __getattribute__(self, name):
        return super(CanvasObject, self).__getattribute__(name)
```
### The Question

That being said, what can I do to fix this?
Thanks!

**Comment by Thetwam** [comment]
Hey @IreTheKID,

As you suspected, it's a limitation of the API. Unfortunately, Canvas doesn't return the body when listing pages, as stated in the comment above the `body` entry in the provided screenshot.

```js
  // the page content, in HTML (present when requesting a single page; omitted
  // when listing pages)
  "body": "<p>Page Content</p>",
```

To my knowledge, there is no way to get the `body` attribute directly when listing multiple pages at once. However, you can still make individual calls to get the page bodies.

```python
# assuming you have a list of pages called `pages` from before
for page in pages:
    new_page = course.get_page(page.url)
    print(new_page.body)
```

---

It's also worth noting that you can iterate directly over the `PaginatedList` returned from `course.get_pages()`. If you still want a proper `list`, you can call `list()` on it.

```python
p = course.get_pages()
pages = list(p)

# or, more concisely
pages = list(course.get_pages())
```

If you want to limit to, say, the first 100 pages, you can do that by slicing.

```python
p = course.get_pages()
pages = list(p[:100])
```

---

Getting each page individually isn't an ideal solution, but unfortunately it's a limitation of Canvas itself, not the `canvasapi` library.

**Comment by IreTheKID** [comment]
Ok, thanks for your help!
