### ISSUE TITLE
get_user through unique_id?

### ISSUE THREAD

**Issue by sodiumchl** [ucfopen/canvasapi#441]
How can I find a user through searching/matching the pseudonym[unique_id] field? I tried get_user(studentID, 'login_id') but it did not work. Or, I could get the user list first and then pick the user with matching login_id, but it is really slow.

**Comment by jessemcbride** [comment]
Hey @sodiumchl,

Looking at the [Object IDs, SIS IDs, and special IDs](https://canvas.instructure.com/doc/api/file.object_ids.html) docs, it's not immediately apparent what `unique_id` would pair to, but using `sis_login_id` (or `sis_user_id`) as the id type argument might behave the way you're expecting.

**Comment by sodiumchl** [comment]
Thanks so much for the quick reply! 
By unique_id I meant the pseudonym[unique_id] field when a user is created. See
https://canvas.instructure.com/doc/api/users.html
We use the student ID for pseudonym[unique_id]. In our case it is different from pseudonym[sis_user_id].

**Comment by jessemcbride** [comment]
No worries! I'm hoping it's not too tricky to get it working correctly.

I was hoping `canvas.get_user(id, id_type="sis_login_id")` would pull a user by their `pseudonym[unique_id]` attribute. That said, I've never actually used the `pseudonym[unique_id]` attribute, so I can't be sure that it'll work. I can take a look at it tomorrow to test out some different options, but before I do, can you confirm that neither `id_type="sis_login_id"` or `id_type="sis_user_id" ` return what you want when passed to `canvas.get_user`?

**Comment by sodiumchl** [comment]
I confirm that "sis_login_id" in get_user() does correspond to pseudonym[unique_id]. In __user.dict__ the field is named just "login_id", but id_type="login_id" does not work with get_user(). Many thanks!
