### ISSUE TITLE
user.delete(), user.activate(); user.deactivate()

### ISSUE THREAD

**Issue by sodiumchl** [ucfopen/canvasapi#442]
These functions would be very helpful: user.delete(), user.activate(); user.deactivate()
But I could not find them in the current canvasapi. Is there any workaround?

**Comment by Thetwam** [comment]
Hey @sodiumchl 

Deleting a user is an account level action, using `Account.delete_user()`

https://canvasapi.readthedocs.io/en/stable/account-ref.html#canvasapi.account.Account.delete_user

I'm not sure what you mean by `user.activate`/`deactivate`, but you can deactivate a user's course enrollments with this method:

https://canvasapi.readthedocs.io/en/stable/enrollment-ref.html#canvasapi.enrollment.Enrollment.deactivate

**Comment by sodiumchl** [comment]
Thanks so much!

For activating a student account, I was referring to the status field (active/deleted) under users.csv here:
https://canvas.instructure.com/doc/api/file.sis_csv.html
I though a student could be deactivated (i.e., suspended, for all courses) for a period of time, and activated again at a later date, without loosing existing data. I imagine this is different from deleting a student. Maybe I did not understand it correctly.
