### ISSUE TITLE
How can I get course enrollments in a section?

### ISSUE THREAD

**Issue by sodiumchl** [ucfopen/canvasapi#446]
How can I get course enrollments in a section? That is, effectively adding a section name to the following:
users = course.get_users(enrollment_type=['student']_, section_name=['2019Fall']_)

**Comment by sodiumchl** [comment]
I tried something like the following. secid does not seem to have any effect. And I don't know if this is the best way to do this.

def get_enrollments(course, secid=0, enrolltype='StudentEnrollment'):
    enrollments=[]
    if course:
        if secid==0:
            enrollments = course.get_enrollments(type=[enrolltype])
        else:
            enrollments = course.get_enrollments(type=[enrolltype], course_section_id=[secid])
    return enrollments

**Comment by eriko** [comment]
Ask the section for it's enrollment.


def import_course_section_enrollment_from_canvas(self, canvas, enrollments):
    if self.c_course is None:
        self.c_course = canvas.get_course(self.course_id, 'sis_course_id')
    c_sections = self.c_course.get_sections()
    for c_section in c_sections:
        c_enrollments = c_section.get_enrollments(role=['StudentEnrollment'],
                                                  state=['active', 'invited'])
        for c_enrollment in c_enrollments:
            print(c_enrollment)
            #c_enrollments
    return None
