### ISSUE TITLE
canvas.get_announcements gives a list of announcements, not the latest announcement in a course.

### ISSUE THREAD

**Issue by SpaceNerden** [ucfopen/canvasapi#453]
When I use `canvas.get_announcements` with a single `course_id`, it returns a `paginated_list` of 2-4 announcements. Is there a way to only get the latest for that course?

**Comment by bennettscience** [comment]
The [Canvas endpoint](https://canvas.instructure.com/doc/api/announcements.html) doesn't allow for much filtering on the announcements list. The best you could do is to either filter by `start_date` or `end_date` as `kwargs` or filter the resulting list manually once you get them all back.

**Comment by SpaceNerden** [comment]
Thanks for clarifying.
