### ISSUE TITLE
Add Support for Delete Rubric 

### ISSUE THREAD

**Issue by fredpyo** [ucfopen/canvasapi#480]
**What resource needs additional coverage?**
Rubrics

**What endpoints need to be covered?**
DELETE /api/v1/courses/:course_id/rubrics/:id
Docs here: https://canvas.instructure.com/doc/api/rubrics.html#method.rubrics.destroy

I looked around the code but I couldn't find this particular call, only references to deleting the rubric associations. Hopefully this bug report is OK.

**Comment by ggarfink** [comment]
I'd be willing to work on this issue. Any other information I should have before I start working on it?

**Comment by Thetwam** [comment]
Hey @ggarfink, thanks for volunteering! Check out the [Contributing Guide](https://github.com/ucfopen/canvasapi/blob/develop/.github/CONTRIBUTING.md) to get started. If you have any questions at all, feel free to post here.

We're also on the [UCF Open Source Slack](https://ucf-open-slackin.herokuapp.com/) in the `#canvasapi` and `#canvasapi-dev` channels for more immediate contact.

Thanks again!

**Comment by Thetwam** [comment]
Resolved in #485
