### ISSUE TITLE
HTTP 500 Internal Server Error with recursive flatten_kwargs

### ISSUE THREAD

**Issue by spble** [ucfopen/canvasapi#494]
When attempting to create a Quiz on canvas, specifying the multiple choice answers using recursive dictionaries causes Canvas to throw an internal server error.

# To Reproduce

Call the `Question` endpoint with the `answers` parameter included as a list of dictionaries. This produces a HTTP POST with data like so in the body:

```
question[question_name]=Question+1(A)&
question[question_text]=This+is+some_question+text&
question[points_possible]=1&
question[question_type]=multiple_choice_question&
question[answers][][answer_html]=text_for_incorrect_answer_1&
question[answers][][answer_weight]=0&
question[answers][][answer_html]=text_for_correct_answer&
question[answers][][answer_weight]=100&
question[answers][][answer_html]=text_for_incorrect_answer_2&
question[answers][][answer_weight]=0&
question[answers][][answer_html]=text_for_incorrect_answer_3&
question[answers][][answer_weight]=0&
```

The response from Canvas is a HTTP 500 Internal Server Error with the content: `{"errors":[{"message":"An error occurred.","error_code":"internal_server_error"}],"error_report_id":######}`

# Expected behavior

This should create a question, within the specified Quiz, with the answers included.

# Environment information

- Python version (`python --version`): *3.9.4*
- CanvasAPI version (`pip show canvasapi`): *2.2.0*

# Additional context

My code that used this endpoint was actually working last week without any issue, there is potentially a change on Canvas' side recently which has modified this behaviour.

I have contacted Canvas support regarding this, and the helpful member of their support team suggested that I try including an index number inside the empty brackets (e.g. `[0]` instead of `[]`).

I modified the `util.py` file to test this, and discovered that it works. PR incoming.

**Comment by spble** [comment]
This only seems to be an issue when the empty square brackets (`[]`) are not the last item.

If, for example, you are submitting an `Assignment`, then you must specify something like:
```
assignment[submission_types][]=online_upload
assignment[submission_types][]=online_url
```
If you perform a similar action, indexing the submission_types like the following:
```
assignment[submission_types][0]=online_upload
assignment[submission_types][1]=online_url
```

Then Canvas throws a HTTP 400 Bad Request error.

This is definitely inconsistent behaviour, and should really be fixed on the Canvas side.

**Comment by kmill** [comment]
What I have found experimentally is that the internal server error is triggered when "answers" is a nonempty list.  If you change it to be a dictionary (or "hash" in Ruby-speak), it seems to circumvent whatever code is causing the error.

I'm currently using a workaround that turns this list into a dictionary before calling `create_question`: https://github.com/UCBMath/pyquiz/blob/main/pyquiz/canvas.py#L82

I don't have my own local installation of Canvas so I haven't been able to properly test it, but I did find a line of code that *might* be the cause.  It was added last month and will raise an error if "answers" is an array but won't if it's a hash:
https://github.com/instructure/canvas-lms/blob/master/app/controllers/quizzes/quiz_questions_controller.rb#L472

**Comment by kmill** [comment]
[Canvas has fixed the issue](https://github.com/instructure/canvas-lms/commit/520d44f1a67c089444654f2ba48c43a226bb716c#diff-2415f540d85fb325f42ff0bd2527c813e32de2ac25bfc5da7b3ab6c987dd6ada) and it's now in the beta.  I've checked that it now works again when `answers` is a list.
