### ISSUE TITLE
Query paramaters and sis ids

### ISSUE THREAD

**Issue by sigurdurb** [ucfopen/canvasapi#50]
Hi, i am new to this api but I like the implementations of it a lot.

A lot of the canvas api accepts query parameters,
Lets take for example [listing users in a course](https://canvas.instructure.com/doc/api/live#!/courses.json/list_users_in_course_users_get_5) where almost every parameter type is query

I would like to be able to add a query parameters for example
/api/v1/courses/{course_id}/users?enrollment_type=student
Is this possible now or how would you suggest the implementation? 

Also, along with that it would also be handy to not use user_id but sis_user_id
and for course_id; sis_course_id. 
However, sis_ids are not a query string. But instead come with a "sis_course_id:" in front of the sis id number itself.
example:
```/api/v1/courses/sis_course_id:{{sis_course_id}}```

Is that possible?, suggest implementation?

Currently I seem to be able to make a custom query like this
This example fetches only students in a course and I have tested it to be working.
```
	canvas = Canvas(API_URL, API_KEY)

	# First, retrieve the Course object
	course = canvas.get_course(COURSE_ID)

	
	'''You can make your own custom request like this'''
	from canvasapi.paginated_list import PaginatedList
	from canvasapi.user import User

	st_users = PaginatedList(User,
					course._requester,
					'GET',
					'courses/{}/users?enrollment_type=student'.format(COURSE_ID)
					,{})
	for st in st_users:
		print(st.id,st.name)
```

**Comment by Thetwam** [comment]
Hi @sigurdurb!

In the current state of the library, this isn't possible yet. However, we have already created a solution to a similar problem for [`get_user`](https://github.com/ucfopen/canvasapi/blob/master/canvasapi/canvas.py#L123). In the case of `get_user`, you can provide an optional argument called `id_type` with values such as `'sis_login_id'` or `'sis_user_id'`, which would be prepended to the id with a colon.

There appears to be several types of objects in Canvas with special ids:
https://canvas.instructure.com/doc/api/file.object_ids.html

Do you think it would be beneficial to apply the solution provided in `get_user` to the other objects?

**Comment by Thetwam** [comment]
My apologies @sigurdurb, I believe my earlier post only addressed the second part of your question.

To get a list of all users in a course with enrollment type student, you can do the following:

```python
canvas = Canvas(API_URL, API_KEY)

# First, retrieve the Course object
course = canvas.get_course(COURSE_ID)

# Grab all users from a course with the 'student' enrollment type
# Note that users is a PaginatedList object
users = course.get_users(enrollment_type='student')

# Loop through users and do what you need.
for user in users:
    print(user)
```

**Comment by Thetwam** [comment]
Hey @sigurdurb,

In the latest release (#52), we added the some functionality that should suit your needs.

When getting a course, account, group, or section, you can add an optional parameter `use_sis_id` to `True` to use the SIS_ID instead of the canvas ID. For example:

```python
canvas = Canvas(API_URL, API_KEY)

# Get a course by Canvas ID
COURSE_ID = 123456
canvas_course = canvas.get_course(COURSE_ID)

# Get a course by SIS ID
SIS_COURSE_ID = 'ENC101'
sis_course = canvas.get_course(SIS_COURSE_ID, use_sis_id=True)
```


Gonna mark this as closed. Feel free to re-open or make a new issue if you have any other questions!
