### ISSUE TITLE
Get all attempts for a quiz

### ISSUE THREAD

**Issue by MatthewJMoreno** [ucfopen/canvasapi#505]
**What resource needs additional coverage?**
Quizzes

**What endpoints need to be covered?**
Currently, [get_submissions](https://canvasapi.readthedocs.io/en/stable/quiz-ref.html#canvasapi.quiz.Quiz.get_submissions) gets only the latest attempt. What I need are all attempts, there is already a [know solution](https://community.canvaslms.com/t5/Canvas-Question-Forum/Get-All-Quiz-Submissions-API-not-working/td-p/218389) to this problem and just needs to be added.

**Comment by Thetwam** [comment]
Hi @MatthewJMoreno,

Have you tried the solution you linked with CanvasAPI? As near as I can tell, it shouldn't require a change to the library to work.

Adding the attempt number (`?attempt=1`) should work like this:

```python
quiz.get_submissions(attempt=1)
```

Including submission history (`include[]=submission_history`) should work like this:

```python
quiz.get_submissions(include=['submission_history'])
```

**Comment by MatthewJMoreno** [comment]
Hello @Thetwam submission_history worked for me. ill close this
