### ISSUE TITLE
stdout flooded with request responses

### ISSUE THREAD

**Issue by tahir-ijaz** [ucfopen/canvasapi#517]
### Discussed in https://github.com/ucfopen/canvasapi/discussions/516

<div type='discussions-op-text'>

<sup>Originally posted by **tahir-ijaz** September  8, 2021</sup>
First of all, thank you so much for _**canvasapi**_, its really awesome! I know this is not really an issue and perhaps I am doing something wrong. I was wondering if there is a way I could silence request responses being logged to stdout. 

For instance, when I try to traverse through enrollments:

```python
for course in account.get_courses(enrollment_term_id=4, per_page=100):
        for enrollment in course.get_enrollments(type="StudentEnrollment", per_page=100):
```

stdout gets flooded with following:

```python
...
Request: GET https://xxxx.instructure.com/api/v1/courses/448/enrollments
Response: GET https://xxxx.instructure.com/api/v1/courses/448/enrollments 200
Request: GET https://xxxx.instructure.com/api/v1/courses/449/enrollments
Response: GET https://xxxx.instructure.com/api/v1/courses/449/enrollments 200
Request: GET https://xxxx.instructure.com/api/v1/courses/450/enrollments
Response: GET https://xxxx.instructure.com/api/v1/courses/450/enrollments 200
Request: GET https://xxxx.instructure.com/api/v1/courses/451/enrollments
Response: GET https://xxxx.instructure.com/api/v1/courses/451/enrollments 200
...
```

I tried setting the logging level to _INFO -> WARNING -> ERROR_ as well as _disabling_ it all together without any success.

Would really appreciate any ideas or suggestions!</div>

**Comment by bennettscience** [comment]
I can't get my terminal to do the same thing. Are you running this from the python shell? Or is it part of the script?

**Comment by tahir-ijaz** [comment]
Thank you so much for your response. That is very interesting. I am running it in a script in virtualenv.

```python
(venv) tahir@macbook ~/dev/csync> python3 sync.py
Request: GET https://xxxxxx.instructure.com/api/v1/accounts/1
Response: GET https://xxxxxx.instructure.com/api/v1/accounts/1 200
Request: GET https://xxxxxx.instructure.com/api/v1/accounts/1/courses
Response: GET https://xxxxxx.instructure.com/api/v1/accounts/1/courses 200
Request: GET https://xxxxxx.instructure.com/api/v1/courses/448/enrollments
Response: GET https://xxxxxx.instructure.com/api/v1/courses/448/enrollments 200
Request: GET https://xxxxxx.instructure.com/api/v1/courses/449/enrollments
Response: GET https://xxxxxx.instructure.com/api/v1/courses/449/enrollments 200
Request: GET https://xxxxxx.instructure.com/api/v1/courses/450/enrollments
Response: GET https://xxxxxx.instructure.com/api/v1/courses/450/enrollments 200```

Following is the only function I am calling:


```python
def get_all_grades(self):
        account = self.canvas.get_account(1)
        courses = account.get_courses(enrollment_term_id=4)

        for course in account.get_courses(enrollment_term_id=4, per_page=100):
            for enrollment in course.get_enrollments(type="StudentEnrollment", per_page=100):
                print(enrollment)
```

**Comment by tahir-ijaz** [comment]
@Thetwam it was me all along! Apologies for bothering you with this. I wrote another script outside of my virtualenv and it ran perfectly (without any stdout flooding). Thank you so much for looking into this for me! and thus making me question my environment. 

 I am sorry, I know this is not the right forum to ask a question, I just wanted to take your opinion about using threads to fetch data using _canvasapi_. What would you think would be a better approach? 

>  (a) initializing multiple canvas connections
>  (b) all threads utilize the same connection
