### ISSUE TITLE
Page editing seems to not be working

### ISSUE THREAD

**Issue by RobertHildebrand** [ucfopen/canvasapi#519]
I'm trying to edit the contents of a page using the API.  The code:

myPage.edit(page = {'title' :  'API_TEST'})

won't change the title.  

Is "page = " the correct thing to put there?  I couldn't find an example of editing a page.  This basic structure works for assignments though.

Thanks for your help!

**Comment by Thetwam** [comment]
According to [Canvas's API Documentation for Updating Pages](https://canvas.instructure.com/doc/api/pages.html#method.wiki_pages_api.update), the prefix is `wiki_page`, not `page`.

This should do the trick!

```python
my_page.edit(wiki_page={"title" : "API_TEST"})
```

**Comment by RobertHildebrand** [comment]
You are amazing!  Thanks!   Really great API.   I'm excited to see what I
can do with it.

*Robert Hildebrand, Ph.D.*
*Assistant Professor*
Pronouns: he/him/his
Redistricting Analytics at Virginia Tech (RAVT
<https://cgit04.cc.vt.edu:2011/>)
Grado Department of Industrial Systems Engineering, Virginia Tech

As a member of the Virginia Tech community, I acknowledge the
Tutelo/Monacan Peoples, who are the traditional custodians of the land upon
which we work and live, and I recognize their continuing connection to the
land, water, and air that Virginia Tech consumes each day. As a land grant
university, we collectively pay our respects to these Nations, and to their
elders past, present, and emerging.

https://www.ise.vt.edu/people/faculty/hildebrand.html
https://sites.google.com/site/robertdhildebrand/
