### ISSUE TITLE
Request to add ePortfolios API

### ISSUE THREAD

**Issue by Birdmaaan4** [ucfopen/canvasapi#525]
**What resource needs additional coverage?**
- ePortfolios API

**What endpoints need to be covered?**
- https://canvas.instructure.com/doc/api/e_portfolios.html

I'm an L3 support engineer at Instructure. I put in a request to have these endpoints added, and engineering delivered. Hope you're as happy as I am; it makes dealing ePortfolio spam easier.

**Comment by bennettscience** [comment]
I don't do much with ePortfolios, so I didn't see this update to the API. Is an `ePortfolioPageObject` a property on an `ePortfolioObject`? I see there's a separate endpoint to get the pages for a given`ePortfolioObject` id, but are those ever returned as a nested array by Canvas?

**Comment by bennettscience** [comment]
I've started a PR for this.

**Comment by bennettscience** [comment]
Ok, I just wanted to make sure the portfolios don't come with an array of pages to parse out.

I have a branch started...hoping to get the tests written tonight so I can open a PR this week.
