### ISSUE TITLE
Project not showing up in Google searches

### ISSUE THREAD

**Issue by spencer1248** [ucfopen/canvasapi#53]
Hi,

Thanks for the great library!

I'm not sure how much you can do about this but you're not getting very good SEO on Google, which is a shame given the high quality of the library. The following terms do not give me a first page result for your Github project:

"canvas api python"
"canvas api"
"canvas lms api"
"canvas lms api client
"canvas lms api python"
"canvas lms api python client"

They at best just yield a couple of unmaintained libraries and I haven't been able to find any search terms that do yield your library except for "canvasapi" which isn't great for discoverability.

I've never had to deal with a problem like this before but maybe there's a way for you to update your README.md to improve your SEO visibility? I started rolling my own client library before I found your library by chance, and since then have spotted many other hastily written API clients and worry that this is causing an issue.

**Comment by spencer1248** [comment]
I should have searched on PyPi, the project has good weight on there for "canvas api" but I'm still learning the Python ecosystem 😛. Still seems like this may be worthwhile.

**Comment by Thetwam** [comment]
Hey @spencer1248,

Thanks for posting this - you're right, we need to work on our SEO. I've spent the last few days researching and chatting with coworkers about this. The consensus seems to be that the most important factor is backlinks from other places on the internet.

In the near future I'll be looking to improve our visibility by posting places like the Canvas Community. If you'd like to help, a good way would be to link the library from any open project you might have that uses it.

I'll leave this issue open as a reminder for us to be thinking about SEO.

**Comment by jackrsteiner** [comment]
Agree! I found lots of other incomplete wrappers before getting lucky and finding this one... days later.

**Comment by jessemcbride** [comment]
It looks like we've finally made it to the top of Google for "Python Canvas API." Our page rank isn't that impressive with Bing or DuckDuckGo, but I'm not sure what we can really do about that beyond staying the course and continuing to develop the library.

I'm going to close this but I'm open to revisiting it if someone else feels like we can do more to improve our SEO.
