### ISSUE TITLE
Updating Scores to a Specific Rubric

### ISSUE THREAD

**Issue by kspicer80** [ucfopen/canvasapi#538]
**What resource needs additional coverage?**
Rubrics

**What endpoints need to be covered?**
Requested here is a method that would allow one to upload scores on a specific rubric for a specific assignment. Ideally this would include the ability to add scores for multiple different criteria within the specified rubric. As @bennettscience noted in a discussion [here](https://github.com/ucfopen/canvasapi/discussions/537#discussioncomment-3132545), one can go directly through the Canvas API, but it would be nice to have a function to handle this from within directly through the canvasapi library itself.

**Comment by bennettscience** [comment]
From what I can tell, these are the missing endpoints for rubric-related things:

- [Create a single rubric assessment](https://canvas.instructure.com/doc/api/rubrics.html#method.rubric_assessments.create)
- [Update a single rubric assessment](https://canvas.instructure.com/doc/api/rubrics.html#method.rubric_assessments.update)
- [Delete a single rubric assessment](https://canvas.instructure.com/doc/api/rubrics.html#method.rubric_assessments.destroy)
- [Create a Rubric Association](https://canvas.instructure.com/doc/api/rubrics.html#method.rubric_associations.create)

**Comment by bennettscience** [comment]
I've started working on these endpoints.
