### ISSUE TITLE
Canvas.list_calendar_events should accept datetime instances

### ISSUE THREAD

**Issue by liblit** [ucfopen/canvasapi#54]
The `Canvas.list_calendar_events` method feeds its parameters down to a `GET /api/v1/calendar_events` request. [That request](https://canvas.instructure.com/doc/api/calendar_events.html#method.calendar_events_api.index) accepts `start_date` and `end_date` parameters, which “should be formatted as: yyyy-mm-dd or ISO 8601 YYYY-MM-DDTHH:MM:SSZ.” When using these parameters from Python, it would be convenient to provide values as Python `datetime` instances. For example, to list events between a course’ start and end dates:

```python
from datetime import datetime, timedelta
soon = datetime.today() + timedelta(weeks=2)
events = canvas.list_calendar_events(end_date=soon)
```

This seems like an obvious way to make the call, but iterating over the result fails using version 0.6.0 of `canvasapi`:

```
canvasapi.exceptions.BadRequest: {'end_date': 'Invalid date or invalid datetime for end_date'}'}
```

The call works if I convert the date into a suitably-formatted (ISO 8601) string:

```python
from datetime import datetime, timedelta
soon = datetime.today() + timedelta(weeks=2)
soon_iso = soon.isoformat()
events = canvas.list_calendar_events(end_date=soon_iso)
```

It would be very convenient if `Canvas.list_calendar_events` could accept parameters in the standard `datetime` a Python programmer would naturally expect to use, and would handle the ISO 8601 conversion internally.

Of course, dates and times appear in many other places in the Canvas API. I am reporting this against `Canvas.list_calendar_events` because that is where it is affecting me right now. But perhaps the best fix would be at a lower level within `canvasapi` so that *every* `datetime` instance is converted using `.isoformat` whenever given as the value of any request parameter. Is there a single, centralized place where that could be done?

**Comment by Thetwam** [comment]
This is an excellent idea! It should be possible to do some pre-processing on the arguments in the `request` method of the `Requester` object, prior to passing to the GET/POST/etc. methods.
