### ISSUE TITLE
Can't get courses I'm enrolled in

### ISSUE THREAD

**Issue by benthecoder** [ucfopen/canvasapi#541]
# Describe the bug

I can't grab the courses I'm enrolled in after running `get_courses`. This is the error I'm getting.

```
AttributeError: 'Course' object has no attribute 'course_code'
```

# To Reproduce

```py
from canvasapi import Canvas
CANVAS_TOKEN = <TOKEN>
API_URL = <URL>

canvas = Canvas(API_URL, CANVAS_TOKEN)
courses = canvas.get_courses()
print(courses[0])
```
# Expected behavior

I expected to get a list of courses I'm enrolled in

# Environment information

- Python version (`python --version`)
```
Python 3.8.10
```
- CanvasAPI version (`pip show canvasapi`)
```
Name: canvasapi
Version: 2.2.0
Summary: API wrapper for the Canvas LMS
Home-page: https://github.com/ucfopen/canvasapi
Author: University of Central Florida - Center for Distributed Learning
Author-email: techrangers@ucf.edu
License: MIT License
Location: /Users/benedictneo/miniforge3/envs/canvas_env/lib/python3.8/site-packages
Requires: pytz, requests
Required-by:
```
# Additional context

**Comment by Thetwam** [comment]
Hey @benthecoder, sorry to hear you're having trouble with the library. It seems like CanvasAPI is returning a `Course` object, but it doesn't contain the course_code for some reason, which is causing the `print` to fail. However, you still should be able to get some information out of that course object as-is. Try printing `courses[0].name` to see if that works instead.

In the short term, you can see all the options available to you by printing out the `vars()` of a course object, and using the attributes that do exist:

```python
for course in courses:
    print(vars(course))
```

Long-term, we can look into changing the default `__str__` behavior (used by `print`) to not require the `course_code`.

**Comment by benthecoder** [comment]
Thanks for the swift response @Thetwam! 

My goal is to get todo items based on my courses. the weird thing is this code used to work a year ago, I think some new changes broke it. I was hoping you could help me achieve my goal.

I tried printing out vars, and I got this which I don't believe is of much use
```
{'_elements': [], '_requester': <canvasapi.requester.Requester object at 0x100863ca0>, '_content_class': <class 'canvasapi.course.Course'>, '_first_url': 'courses', '_first_params': {'_kwargs': [], 'per_page': 100}, '_next_url': 'courses', '_next_params': {'_kwargs': [], 'per_page': 100}, '_extra_attribs': {}, '_request_method': 'GET', '_root': None}
```

**Comment by Thetwam** [comment]
That appears to be the `vars()` of a `PaginatedList` object, presumably `vars(courses)`. Could you try running  `vars(courses[0])` or in the loop that I suggested above?

**Comment by benthecoder** [comment]
ah thanks, I'm able to get the id and course names now. Thanks!
