### ISSUE TITLE
Submission methods on wrong class

### ISSUE THREAD

**Issue by Thetwam** [ucfopen/canvasapi#57]
Was working with assignment submissions recently and discovered that many of the methods relating to submissions are in the wrong class. For example, `list_submissions`appears in the `Course` and `Section` classes, but should probably just be in the `Assignment` class.

Need to move them to the appropriate class.

**Comment by Thetwam** [comment]
After some thought, It seems irresponsible to simply move the methods in one step. A developer using `canvasapi` may already have written code using the methods, and moving them would break their code without warning.

Instead, the next version of `canvasapi` will implement new versions of the methods, but leave the old ones intact. When a developer tries to use these methods, a deprecation warning will be thrown that will urge them to use the new methods before upgrading to future version of the library.

**Comment by Thetwam** [comment]
Apparently Canvas doesn't allow you to just get an assignment from a section. However, you can still get submissions for a section.

Specifically, this is valid:
```
GET /api/v1/sections/:section_id/assignments/:assignment_id/submissions
```
... but this is not:
```
GET /api/v1/sections/:section_id/assignments/:assignment_id
```

This presents a problem with moving `list_submissions` from the `Section` class. Due to the way we structure our calls, there is no way to have an `Assignment` object created from a `Section` object that we could then `list_submissions` on

However, it looks like we can still proceed with moving the method in `Course` to `Assignment`.

**Comment by jessemcbride** [comment]
We should come up with a more comprehensive list of section weirdness and then submit a bug report / feature request to Canvas.
