### ISSUE TITLE
Add Support for List Files

### ISSUE THREAD

**Issue by rebelaide** [ucfopen/canvasapi#6]
Please add support for the listing files endpoint

Documentation: https://canvas.instructure.com/doc/api/files.html#method.files.api_index
- GET /api/v1/courses/:course_id/files
- GET /api/v1/users/:user_id/files
- GET /api/v1/groups/:group_id/files
- GET /api/v1/folders/:id/files

Please include all the the parameters.

**Comment by Thetwam** [comment]
Resolved in #17
