### ISSUE TITLE
canvas create conversation cannot set subject

### ISSUE THREAD

**Issue by scott-yj-yang** [ucfopen/canvasapi#618]
# canvas create conversation cannot set subject

When using `canvas.create_conversation`, passing the kwargs of `subject` does not correctly set the subject of the canvas conversation.

# To Reproduce

1. authenticate canvas,
2. `canvas.create_conversation([121039],
                                  body="Why there is no subject!",
                                  subject="Subject of this conversation"
                                 )`
3. 
<img width="461" alt="image" src="https://user-images.githubusercontent.com/67733409/235546062-547071d9-dc07-4ee7-96cb-c8be491061b7.png">

# Expected behavior

The Subject should be `Subject of this conversation` instead of `(No Subject)`

# Environment information

- Python version 3.10.9
- CanvasAPI version Version: 3.1.0

**Comment by scott-yj-yang** [comment]
Sorry, I guess that's the issue of the grader account. When send to normal enrolled user, the subject shown up.

**Comment by Thetwam** [comment]
@scott-yj-yang For what it's worth, the docs say the subject "is ignored when reusing a conversation". It's also possible that an old thread with no subject was being re-used. If that's a concern, you can set `force_new` to `True`, and it should create a new thread with the defined subject.

Best of luck!

**Comment by scott-yj-yang** [comment]
Thanks! I deleted the old thread on the canvas UI (img below). But maybe this is only a lazy deletion on the backend of canvas.
<img width="289" alt="image" src="https://user-images.githubusercontent.com/67733409/235548091-7939444b-de2d-496b-9884-9da40e783e89.png">

Regardless, thank you so much for your quick response!
