### ISSUE TITLE
Include Initiator-Only Conversations in API Endpoint

### ISSUE THREAD

**Issue by ChocoTonic** [ucfopen/canvasapi#641]
**What resource needs additional coverage?**
Conversations

**What endpoints need to be covered?**
https://canvas.instructure.com/doc/api/conversations.html

I noticed that conversation pulls only the conversations that involve both people in the conversation, and cannot capture the conversation initiated by you (Sent) without a response.

is there something I'm missing in the documentation?

**Comment by ChocoTonic** [comment]
it looks like `sent` is a valid scope for search that I found in the API docs but it's not documented on the canvasapi docs

**Comment by bennettscience** [comment]
Any request parameter in the Canvas docs can be [passed as a keyword argument](https://canvasapi.readthedocs.io/en/stable/keyword-args.html). Trying to document all of the options on every endpoint would be too much to try and maintain.

**Comment by Thetwam** [comment]
Closing as wontfix.
