### ISSUE TITLE
Creating Quiz Questions

### ISSUE THREAD

**Issue by felkezac** [ucfopen/canvasapi#649]
### Discussed in https://github.com/ucfopen/canvasapi/discussions/648

<div type='discussions-op-text'>

<sup>Originally posted by **felkezac** April 19, 2024</sup>
I am having trouble creating or editing quiz questions. Regardless what I have tried, it generates a blank question. Attempts to edit the question throw error 500. Am I missing something?

One thing I have tried:
bar = {'question_name': 'asdf', 'question_type': 'numerical_question', 'question_text': 'asdfasdf'}
item = q.create_question(**bar)</div>

**Comment by bennettscience** [comment]
Answered more fully in #648.
