### ISSUE TITLE
Pagination next_link breaking with get_new_quizzes

### ISSUE THREAD

**Issue by stelpstraATeur** [ucfopen/canvasapi#663]
Pagination is breaking showing the following message:

```
  File "C:\Python\Envs\test_env\lib\site-packages\canvasapi\paginated_list.py", line 49, in __iter__
    new_elements = self._grow()
  File "C:\Python\Envs\test_env\lib\site-packages\canvasapi\paginated_list.py", line 111, in _grow
    new_elements = self._get_next_page()
  File "C:\Python\Envs\test_env\lib\site-packages\canvasapi\paginated_list.py", line 84, in _get_next_page
    re.search(regex, next_link["url"]).group(1) if next_link else None
AttributeError: 'NoneType' object has no attribute 'group'
```

Course with less than 50 New Quizzes don't cause any issues, but it happens in the situations:
- when a quiz copy failed and the try again button is displayed
- having over 50 New Quizzes in one course

- Create more than 50 New Quiz type quizzes
- Get data using get_new_quizzes (https://canvasapi.readthedocs.io/en/stable/course-ref.html?highlight=quizzes#canvasapi.course.Course.get_new_quizzes) and iterate through the results.

# Environment information:
- Python version: 3.10.6
- CanvasAPI version: 3.2.0

Could it be related to what is mentioned in this blog post [Forthcoming Update to Canvas API Response Header Capitalization](https://community.canvaslms.com/t5/The-Product-Blog/Forthcoming-Update-to-Canvas-API-Response-Header-Capitalization/ba-p/604018)?

**Comment by jonespm** [comment]
I don't see that limit set [anywhere in the documentation for new quizzes ](https://canvas.instructure.com/doc/api/new_quizzes.html) and possibly nobody tested with more than 50 quizzes.

So this should probably be changed in the code for new quizzes if that is the limit, but you can work around it locally by passing a `per_page` parameter to see if that fixes it

`new_quizzes(per_page=50)`
