### ISSUE TITLE
getting-started.rst Canvas object's order of arguments is inconsistent

### ISSUE THREAD

**Issue by stephenwoosley** [ucfopen/canvasapi#71]
I'm just starting out with both Python and canvasapi (and very excited about what you all have shared here!), and was using your getting-started guide to get up and going. I noticed this line at [the Usage section](https://github.com/ucfopen/canvasapi/blob/master/docs/getting-started.rst#usage):

`canvas = Canvas(API_URL, API_KEY)`

Then a few lines down the page under [Examples](https://github.com/ucfopen/canvasapi/blob/master/docs/getting-started.rst#examples), the order of the arguments is switched:

`canvas = Canvas(API_KEY, API_URL)` (repeated twice in the Examples section)

This could be confusing for beginners like me.

Thanks again for sharing your work! Looking forward to digging into the functionality some more.

**Comment by jessemcbride** [comment]
Yikes! That's outdated. We need to update our documentation 😨.

Check out the updated quickstart in our [README](https://github.com/ucfopen/canvasapi#quickstart). It should get you up and running without much trouble.

Thanks for bringing this to our attention. Feel free to ping us on [Slack](https://ucf-open-slackin.herokuapp.com/) in #canvasapi if you have any questions.

**Comment by Thetwam** [comment]
Did a quick fix for this in 8366df973e059e7b30f74578c470c698633f856a. We should probably still update the getting-started guide to reflect the changes we made to the README a while back.
