### ISSUE TITLE
Page.edit fails, reporting that 'Page' object has no attribute 'id'

### ISSUE THREAD

**Issue by liblit** [ucfopen/canvasapi#72]
Using `canvasapi` 0.6.0, I have a `Page` object obtained by calling `Course.get_page`. I try to unpublish this page by calling `page.edit(wiki_page={'published': 'false'})`. (I use `'false'` instead of `False` to avoid any possible additional instance of issue #64.)

Unfortunately, this `Page.edit` call fails:

```python
  File "/home/liblit/.local/lib/python3.6/site-packages/canvasapi/page.py", line 33, in edit
    page_json.update({'course_id': self.id})
AttributeError: 'Page' object has no attribute 'id'
```

Printing `dir(page)` shows that while `page` indeed has no `id` attribute, it does have `course_id`, `page_id`, and `parent_id` attributes. Manually setting `page.id = page.page_id` before the `Page.edit` call does seem to fix the problem, though of course that is only a workaround.

**Comment by Thetwam** [comment]
This is a bug on our end, unrelated to the Boolean issues.

It's related to our solution to Pages not knowing what course they are in. When we manually add the `course_id` attribute, we accidentally set it to `id` (which isn't a thing, pages have a `url` not an `id`). Should be fixed with #74.
