### ISSUE TITLE
Grouped Responses

### ISSUE THREAD

**Issue by Thetwam** [ucfopen/canvasapi#77]
The `list_multiple_submissions` methods on `Course` and `Section` objects takes in an optional parameter `grouped` (See [Canvas Docs](https://canvas.instructure.com/doc/api/submissions.html#method.submissions_api.for_students)). If `grouped` is true (note: see #61 for details on boolean weirdness for this particular method), the format Canvas returns is different than what PaginatedList normally expects.

To get around this, we prevent the `grouped` parameter from being passed at all. Ideally, we should see if it's possible to parse this other format and leverage it's benefit of being grouped by user.

Similar issues may exist in other endpoints. It's possible that support for different formats is related to #56.

**Comment by bennettscience** [comment]
I'm in a situation where I need grouped submissions, and I know rewriting the models takes a lot more work to get it into the library properly, but wouldn't it make more sense to allow the user to call grouped data and have the warning prompt them to process the `Submissions` themselves?

My solution was to format each submission as JSON using `.to_json()` and then manipulate with the standard `JSON` library. For instance:

```
data = []
course = canvas.get_course(123456)
assigns = course.get_multiple_submissions(student_ids='all', assignment_ids=(111111, 111122, ...), grouped=1)

for a in assigns:
    data.append(json.loads(a.to_json()))

for item in data:
     # do whatever formatting you want with JSON
```

It's a little brute force, but it works. Reenabling the `grouped` flag in the method `**kwargs` makes it easier and faster to get multiple, specific assignments. I'd like to be able to deploy the project I'm working on eventually and it'd be a bummer to have to fork and reference a custom build of the library for that one option.

(Love the library, by the way. Thanks for releasing and maintaining such a great tool.)

**Comment by bennettscience** [comment]
I'm moving some methods over to the `Section` module and this limit also exists for `section.list_multple_submissions` on line 245.

         if 'grouped' in kwargs:
             warnings.warn('The `grouped` parameter must be empty. Removing kwarg `grouped`.')
             del kwargs['grouped']
