### ISSUE TITLE
Support uploading files for submission comments

### ISSUE THREAD

**Issue by liblit** [ucfopen/canvasapi#79]
As far as I can tell, `canvasapi` 0.6.0 has no support for [uploading files to be used in submission comments](https://canvas.instructure.com/doc/api/submission_comments.html). I would like to automate parts of my grading workflow that require this capability. It would be nice for `canvasapi` to help me get that done.

Note that [the complete file-upload workflow](https://canvas.instructure.com/doc/api/file.file_uploads.html) is rather complex. It would be great to have an elegant `canvasapi` interface that simplifies all of this. Barring that, access to each of the primitive steps would at least be better than nothing.

**Comment by Thetwam** [comment]
>It would be great to have an elegant canvasapi interface that simplifies all of this.

We have an `Uploader` class in upload.py that handles file uploads. We should be able to implement this much the same way we did for `Course.upload()`, `User.upload()`, and `Group.upload()`

**Comment by liblit** [comment]
That would be ... absolutely perfect!
