### ISSUE TITLE
Accept path-like objects for file uploads

### ISSUE THREAD

**Issue by liblit** [ucfopen/canvasapi#97]
Under `canvasapi` 0.7.0, `canvasapi.upload.Uploader.__init__` allows two ways to identify the file to be uploaded: it may be given as a string filename, or as an already-open file object. However, there are other ways to describe paths to files besides just strings: what the Python documentation calls “[path-like objects](https://docs.python.org/3/glossary.html#term-path-like-object).” For example:

- From Python 3.4 onward, the [`pathlib`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath) module provides a rich API for manipulating filesystem paths as path-like objects rather than as strings.

- From Python 3.6 onward, the [`os.DirEntry`](https://docs.python.org/3/library/os.html#os.DirEntry) objects returned by [`os.scandir`](https://docs.python.org/3/library/os.html#os.scandir) are path-like objects.

As far as I can tell, the `Uploader` class will not behave correctly if constructed with a path-like object as its `file` argument. This should be improved so that path-like objects are treated like openable filenames, rather than being assumed to be already-open files.

<hr/>

Python 3.6 added several library features to make it easier to write code that transparently handles both string paths as well as path-like objects:

- A new [`os.PathLike`](https://docs.python.org/3/library/os.html#os.PathLike) abstract base class makes it possible to recognize path-like objects in a generic way, rather than checking for specific concrete classes.

- A new [`os.fspath`](https://docs.python.org/3/library/os.html#os.fspath) function returns the string representation of a path-like object, or simply returns its argument unchanged if that argument is already a string.

- Improvements to [`os.open`](https://docs.python.org/3/library/os.html#os.open) and other standard library functions allow them to accept either path-like objects or strings as arguments.

The Python 3.6 release notes include [more information on how to use these features](https://docs.python.org/3/whatsnew/3.6.html#pep-519-adding-a-file-system-path-protocol).

Unfortunately, those Python 3.6 improvements still leave a gap: Python 3.4 and 3.5 have the `pathlib` module, but do not have `os.PathLike`, `os.fspath`, the improvements to `os.open`, etc. Supporting path-like objects in these earlier Python releases may be inconvenient, or perhaps not worth doing at all.

**Comment by theunkn0wn1** [comment]
With python <= 3.5 [being EOL](https://devguide.python.org/devcycle/#end-of-life-branches), Does this package still need to support them?

Would a `python >= 3.6` solution be acceptable?

**Comment by Thetwam** [comment]
@theunkn0wn1 As of CanvasAPI v1.0.0, we only support Python 3.6+, so that would be acceptable.
